// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.29.4
// source: proto/voice/voice.proto

package voice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	VoiceService_CreateConference_FullMethodName          = "/voice.VoiceService/CreateConference"
	VoiceService_GetConference_FullMethodName             = "/voice.VoiceService/GetConference"
	VoiceService_GetConferenceByFSName_FullMethodName     = "/voice.VoiceService/GetConferenceByFSName"
	VoiceService_ListConferences_FullMethodName           = "/voice.VoiceService/ListConferences"
	VoiceService_ListAllActiveConferences_FullMethodName  = "/voice.VoiceService/ListAllActiveConferences"
	VoiceService_EndConference_FullMethodName             = "/voice.VoiceService/EndConference"
	VoiceService_JoinConference_FullMethodName            = "/voice.VoiceService/JoinConference"
	VoiceService_LeaveConference_FullMethodName           = "/voice.VoiceService/LeaveConference"
	VoiceService_GetParticipants_FullMethodName           = "/voice.VoiceService/GetParticipants"
	VoiceService_MuteParticipant_FullMethodName           = "/voice.VoiceService/MuteParticipant"
	VoiceService_KickParticipant_FullMethodName           = "/voice.VoiceService/KickParticipant"
	VoiceService_InitiateCall_FullMethodName              = "/voice.VoiceService/InitiateCall"
	VoiceService_AnswerCall_FullMethodName                = "/voice.VoiceService/AnswerCall"
	VoiceService_HangupCall_FullMethodName                = "/voice.VoiceService/HangupCall"
	VoiceService_GetCall_FullMethodName                   = "/voice.VoiceService/GetCall"
	VoiceService_GetCallHistory_FullMethodName            = "/voice.VoiceService/GetCallHistory"
	VoiceService_GetVertoCredentials_FullMethodName       = "/voice.VoiceService/GetVertoCredentials"
	VoiceService_StartChatCall_FullMethodName             = "/voice.VoiceService/StartChatCall"
	VoiceService_ScheduleConference_FullMethodName        = "/voice.VoiceService/ScheduleConference"
	VoiceService_CreateAdHocFromChat_FullMethodName       = "/voice.VoiceService/CreateAdHocFromChat"
	VoiceService_UpdateRSVP_FullMethodName                = "/voice.VoiceService/UpdateRSVP"
	VoiceService_UpdateParticipantRole_FullMethodName     = "/voice.VoiceService/UpdateParticipantRole"
	VoiceService_AddParticipants_FullMethodName           = "/voice.VoiceService/AddParticipants"
	VoiceService_RemoveParticipant_FullMethodName         = "/voice.VoiceService/RemoveParticipant"
	VoiceService_ListScheduledConferences_FullMethodName  = "/voice.VoiceService/ListScheduledConferences"
	VoiceService_GetChatConferences_FullMethodName        = "/voice.VoiceService/GetChatConferences"
	VoiceService_CancelConference_FullMethodName          = "/voice.VoiceService/CancelConference"
	VoiceService_GetConferenceHistory_FullMethodName      = "/voice.VoiceService/GetConferenceHistory"
	VoiceService_ListChatConferenceHistory_FullMethodName = "/voice.VoiceService/ListChatConferenceHistory"
	VoiceService_GetConferenceMessages_FullMethodName     = "/voice.VoiceService/GetConferenceMessages"
	VoiceService_GetModeratorActions_FullMethodName       = "/voice.VoiceService/GetModeratorActions"
)

// VoiceServiceClient is the client API for VoiceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VoiceService provides audio conferencing and calling capabilities
type VoiceServiceClient interface {
	// Conference management
	CreateConference(ctx context.Context, in *CreateConferenceRequest, opts ...grpc.CallOption) (*Conference, error)
	GetConference(ctx context.Context, in *GetConferenceRequest, opts ...grpc.CallOption) (*Conference, error)
	GetConferenceByFSName(ctx context.Context, in *GetConferenceByFSNameRequest, opts ...grpc.CallOption) (*Conference, error)
	ListConferences(ctx context.Context, in *ListConferencesRequest, opts ...grpc.CallOption) (*ListConferencesResponse, error)
	ListAllActiveConferences(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListConferencesResponse, error)
	EndConference(ctx context.Context, in *EndConferenceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Participant management
	JoinConference(ctx context.Context, in *JoinConferenceRequest, opts ...grpc.CallOption) (*Participant, error)
	LeaveConference(ctx context.Context, in *LeaveConferenceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetParticipants(ctx context.Context, in *GetParticipantsRequest, opts ...grpc.CallOption) (*GetParticipantsResponse, error)
	MuteParticipant(ctx context.Context, in *MuteParticipantRequest, opts ...grpc.CallOption) (*Participant, error)
	KickParticipant(ctx context.Context, in *KickParticipantRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Direct calls (1-on-1)
	InitiateCall(ctx context.Context, in *InitiateCallRequest, opts ...grpc.CallOption) (*Call, error)
	AnswerCall(ctx context.Context, in *AnswerCallRequest, opts ...grpc.CallOption) (*Call, error)
	HangupCall(ctx context.Context, in *HangupCallRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetCall(ctx context.Context, in *GetCallRequest, opts ...grpc.CallOption) (*Call, error)
	GetCallHistory(ctx context.Context, in *GetCallHistoryRequest, opts ...grpc.CallOption) (*GetCallHistoryResponse, error)
	// Authentication & Quick actions
	GetVertoCredentials(ctx context.Context, in *GetVertoCredentialsRequest, opts ...grpc.CallOption) (*VertoCredentials, error)
	StartChatCall(ctx context.Context, in *StartChatCallRequest, opts ...grpc.CallOption) (*StartChatCallResponse, error)
	// Scheduled events
	ScheduleConference(ctx context.Context, in *ScheduleConferenceRequest, opts ...grpc.CallOption) (*Conference, error)
	CreateAdHocFromChat(ctx context.Context, in *CreateAdHocFromChatRequest, opts ...grpc.CallOption) (*Conference, error)
	UpdateRSVP(ctx context.Context, in *UpdateRSVPRequest, opts ...grpc.CallOption) (*Participant, error)
	UpdateParticipantRole(ctx context.Context, in *UpdateParticipantRoleRequest, opts ...grpc.CallOption) (*Participant, error)
	AddParticipants(ctx context.Context, in *AddParticipantsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveParticipant(ctx context.Context, in *RemoveParticipantRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListScheduledConferences(ctx context.Context, in *ListScheduledConferencesRequest, opts ...grpc.CallOption) (*ListScheduledConferencesResponse, error)
	GetChatConferences(ctx context.Context, in *GetChatConferencesRequest, opts ...grpc.CallOption) (*GetChatConferencesResponse, error)
	CancelConference(ctx context.Context, in *CancelConferenceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Conference history
	GetConferenceHistory(ctx context.Context, in *GetConferenceHistoryRequest, opts ...grpc.CallOption) (*ConferenceHistoryResponse, error)
	ListChatConferenceHistory(ctx context.Context, in *ListChatConferenceHistoryRequest, opts ...grpc.CallOption) (*ListChatConferenceHistoryResponse, error)
	GetConferenceMessages(ctx context.Context, in *GetConferenceMessagesRequest, opts ...grpc.CallOption) (*GetConferenceMessagesResponse, error)
	GetModeratorActions(ctx context.Context, in *GetModeratorActionsRequest, opts ...grpc.CallOption) (*GetModeratorActionsResponse, error)
}

type voiceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVoiceServiceClient(cc grpc.ClientConnInterface) VoiceServiceClient {
	return &voiceServiceClient{cc}
}

func (c *voiceServiceClient) CreateConference(ctx context.Context, in *CreateConferenceRequest, opts ...grpc.CallOption) (*Conference, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Conference)
	err := c.cc.Invoke(ctx, VoiceService_CreateConference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) GetConference(ctx context.Context, in *GetConferenceRequest, opts ...grpc.CallOption) (*Conference, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Conference)
	err := c.cc.Invoke(ctx, VoiceService_GetConference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) GetConferenceByFSName(ctx context.Context, in *GetConferenceByFSNameRequest, opts ...grpc.CallOption) (*Conference, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Conference)
	err := c.cc.Invoke(ctx, VoiceService_GetConferenceByFSName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) ListConferences(ctx context.Context, in *ListConferencesRequest, opts ...grpc.CallOption) (*ListConferencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConferencesResponse)
	err := c.cc.Invoke(ctx, VoiceService_ListConferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) ListAllActiveConferences(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListConferencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConferencesResponse)
	err := c.cc.Invoke(ctx, VoiceService_ListAllActiveConferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) EndConference(ctx context.Context, in *EndConferenceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, VoiceService_EndConference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) JoinConference(ctx context.Context, in *JoinConferenceRequest, opts ...grpc.CallOption) (*Participant, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Participant)
	err := c.cc.Invoke(ctx, VoiceService_JoinConference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) LeaveConference(ctx context.Context, in *LeaveConferenceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, VoiceService_LeaveConference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) GetParticipants(ctx context.Context, in *GetParticipantsRequest, opts ...grpc.CallOption) (*GetParticipantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetParticipantsResponse)
	err := c.cc.Invoke(ctx, VoiceService_GetParticipants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) MuteParticipant(ctx context.Context, in *MuteParticipantRequest, opts ...grpc.CallOption) (*Participant, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Participant)
	err := c.cc.Invoke(ctx, VoiceService_MuteParticipant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) KickParticipant(ctx context.Context, in *KickParticipantRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, VoiceService_KickParticipant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) InitiateCall(ctx context.Context, in *InitiateCallRequest, opts ...grpc.CallOption) (*Call, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Call)
	err := c.cc.Invoke(ctx, VoiceService_InitiateCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) AnswerCall(ctx context.Context, in *AnswerCallRequest, opts ...grpc.CallOption) (*Call, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Call)
	err := c.cc.Invoke(ctx, VoiceService_AnswerCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) HangupCall(ctx context.Context, in *HangupCallRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, VoiceService_HangupCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) GetCall(ctx context.Context, in *GetCallRequest, opts ...grpc.CallOption) (*Call, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Call)
	err := c.cc.Invoke(ctx, VoiceService_GetCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) GetCallHistory(ctx context.Context, in *GetCallHistoryRequest, opts ...grpc.CallOption) (*GetCallHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCallHistoryResponse)
	err := c.cc.Invoke(ctx, VoiceService_GetCallHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) GetVertoCredentials(ctx context.Context, in *GetVertoCredentialsRequest, opts ...grpc.CallOption) (*VertoCredentials, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VertoCredentials)
	err := c.cc.Invoke(ctx, VoiceService_GetVertoCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) StartChatCall(ctx context.Context, in *StartChatCallRequest, opts ...grpc.CallOption) (*StartChatCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartChatCallResponse)
	err := c.cc.Invoke(ctx, VoiceService_StartChatCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) ScheduleConference(ctx context.Context, in *ScheduleConferenceRequest, opts ...grpc.CallOption) (*Conference, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Conference)
	err := c.cc.Invoke(ctx, VoiceService_ScheduleConference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) CreateAdHocFromChat(ctx context.Context, in *CreateAdHocFromChatRequest, opts ...grpc.CallOption) (*Conference, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Conference)
	err := c.cc.Invoke(ctx, VoiceService_CreateAdHocFromChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) UpdateRSVP(ctx context.Context, in *UpdateRSVPRequest, opts ...grpc.CallOption) (*Participant, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Participant)
	err := c.cc.Invoke(ctx, VoiceService_UpdateRSVP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) UpdateParticipantRole(ctx context.Context, in *UpdateParticipantRoleRequest, opts ...grpc.CallOption) (*Participant, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Participant)
	err := c.cc.Invoke(ctx, VoiceService_UpdateParticipantRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) AddParticipants(ctx context.Context, in *AddParticipantsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, VoiceService_AddParticipants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) RemoveParticipant(ctx context.Context, in *RemoveParticipantRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, VoiceService_RemoveParticipant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) ListScheduledConferences(ctx context.Context, in *ListScheduledConferencesRequest, opts ...grpc.CallOption) (*ListScheduledConferencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListScheduledConferencesResponse)
	err := c.cc.Invoke(ctx, VoiceService_ListScheduledConferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) GetChatConferences(ctx context.Context, in *GetChatConferencesRequest, opts ...grpc.CallOption) (*GetChatConferencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChatConferencesResponse)
	err := c.cc.Invoke(ctx, VoiceService_GetChatConferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) CancelConference(ctx context.Context, in *CancelConferenceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, VoiceService_CancelConference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) GetConferenceHistory(ctx context.Context, in *GetConferenceHistoryRequest, opts ...grpc.CallOption) (*ConferenceHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConferenceHistoryResponse)
	err := c.cc.Invoke(ctx, VoiceService_GetConferenceHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) ListChatConferenceHistory(ctx context.Context, in *ListChatConferenceHistoryRequest, opts ...grpc.CallOption) (*ListChatConferenceHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChatConferenceHistoryResponse)
	err := c.cc.Invoke(ctx, VoiceService_ListChatConferenceHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) GetConferenceMessages(ctx context.Context, in *GetConferenceMessagesRequest, opts ...grpc.CallOption) (*GetConferenceMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConferenceMessagesResponse)
	err := c.cc.Invoke(ctx, VoiceService_GetConferenceMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) GetModeratorActions(ctx context.Context, in *GetModeratorActionsRequest, opts ...grpc.CallOption) (*GetModeratorActionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModeratorActionsResponse)
	err := c.cc.Invoke(ctx, VoiceService_GetModeratorActions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VoiceServiceServer is the server API for VoiceService service.
// All implementations must embed UnimplementedVoiceServiceServer
// for forward compatibility
//
// VoiceService provides audio conferencing and calling capabilities
type VoiceServiceServer interface {
	// Conference management
	CreateConference(context.Context, *CreateConferenceRequest) (*Conference, error)
	GetConference(context.Context, *GetConferenceRequest) (*Conference, error)
	GetConferenceByFSName(context.Context, *GetConferenceByFSNameRequest) (*Conference, error)
	ListConferences(context.Context, *ListConferencesRequest) (*ListConferencesResponse, error)
	ListAllActiveConferences(context.Context, *emptypb.Empty) (*ListConferencesResponse, error)
	EndConference(context.Context, *EndConferenceRequest) (*emptypb.Empty, error)
	// Participant management
	JoinConference(context.Context, *JoinConferenceRequest) (*Participant, error)
	LeaveConference(context.Context, *LeaveConferenceRequest) (*emptypb.Empty, error)
	GetParticipants(context.Context, *GetParticipantsRequest) (*GetParticipantsResponse, error)
	MuteParticipant(context.Context, *MuteParticipantRequest) (*Participant, error)
	KickParticipant(context.Context, *KickParticipantRequest) (*emptypb.Empty, error)
	// Direct calls (1-on-1)
	InitiateCall(context.Context, *InitiateCallRequest) (*Call, error)
	AnswerCall(context.Context, *AnswerCallRequest) (*Call, error)
	HangupCall(context.Context, *HangupCallRequest) (*emptypb.Empty, error)
	GetCall(context.Context, *GetCallRequest) (*Call, error)
	GetCallHistory(context.Context, *GetCallHistoryRequest) (*GetCallHistoryResponse, error)
	// Authentication & Quick actions
	GetVertoCredentials(context.Context, *GetVertoCredentialsRequest) (*VertoCredentials, error)
	StartChatCall(context.Context, *StartChatCallRequest) (*StartChatCallResponse, error)
	// Scheduled events
	ScheduleConference(context.Context, *ScheduleConferenceRequest) (*Conference, error)
	CreateAdHocFromChat(context.Context, *CreateAdHocFromChatRequest) (*Conference, error)
	UpdateRSVP(context.Context, *UpdateRSVPRequest) (*Participant, error)
	UpdateParticipantRole(context.Context, *UpdateParticipantRoleRequest) (*Participant, error)
	AddParticipants(context.Context, *AddParticipantsRequest) (*emptypb.Empty, error)
	RemoveParticipant(context.Context, *RemoveParticipantRequest) (*emptypb.Empty, error)
	ListScheduledConferences(context.Context, *ListScheduledConferencesRequest) (*ListScheduledConferencesResponse, error)
	GetChatConferences(context.Context, *GetChatConferencesRequest) (*GetChatConferencesResponse, error)
	CancelConference(context.Context, *CancelConferenceRequest) (*emptypb.Empty, error)
	// Conference history
	GetConferenceHistory(context.Context, *GetConferenceHistoryRequest) (*ConferenceHistoryResponse, error)
	ListChatConferenceHistory(context.Context, *ListChatConferenceHistoryRequest) (*ListChatConferenceHistoryResponse, error)
	GetConferenceMessages(context.Context, *GetConferenceMessagesRequest) (*GetConferenceMessagesResponse, error)
	GetModeratorActions(context.Context, *GetModeratorActionsRequest) (*GetModeratorActionsResponse, error)
	mustEmbedUnimplementedVoiceServiceServer()
}

// UnimplementedVoiceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVoiceServiceServer struct {
}

func (UnimplementedVoiceServiceServer) CreateConference(context.Context, *CreateConferenceRequest) (*Conference, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConference not implemented")
}
func (UnimplementedVoiceServiceServer) GetConference(context.Context, *GetConferenceRequest) (*Conference, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConference not implemented")
}
func (UnimplementedVoiceServiceServer) GetConferenceByFSName(context.Context, *GetConferenceByFSNameRequest) (*Conference, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConferenceByFSName not implemented")
}
func (UnimplementedVoiceServiceServer) ListConferences(context.Context, *ListConferencesRequest) (*ListConferencesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConferences not implemented")
}
func (UnimplementedVoiceServiceServer) ListAllActiveConferences(context.Context, *emptypb.Empty) (*ListConferencesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAllActiveConferences not implemented")
}
func (UnimplementedVoiceServiceServer) EndConference(context.Context, *EndConferenceRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndConference not implemented")
}
func (UnimplementedVoiceServiceServer) JoinConference(context.Context, *JoinConferenceRequest) (*Participant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinConference not implemented")
}
func (UnimplementedVoiceServiceServer) LeaveConference(context.Context, *LeaveConferenceRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveConference not implemented")
}
func (UnimplementedVoiceServiceServer) GetParticipants(context.Context, *GetParticipantsRequest) (*GetParticipantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetParticipants not implemented")
}
func (UnimplementedVoiceServiceServer) MuteParticipant(context.Context, *MuteParticipantRequest) (*Participant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MuteParticipant not implemented")
}
func (UnimplementedVoiceServiceServer) KickParticipant(context.Context, *KickParticipantRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KickParticipant not implemented")
}
func (UnimplementedVoiceServiceServer) InitiateCall(context.Context, *InitiateCallRequest) (*Call, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateCall not implemented")
}
func (UnimplementedVoiceServiceServer) AnswerCall(context.Context, *AnswerCallRequest) (*Call, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnswerCall not implemented")
}
func (UnimplementedVoiceServiceServer) HangupCall(context.Context, *HangupCallRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HangupCall not implemented")
}
func (UnimplementedVoiceServiceServer) GetCall(context.Context, *GetCallRequest) (*Call, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCall not implemented")
}
func (UnimplementedVoiceServiceServer) GetCallHistory(context.Context, *GetCallHistoryRequest) (*GetCallHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCallHistory not implemented")
}
func (UnimplementedVoiceServiceServer) GetVertoCredentials(context.Context, *GetVertoCredentialsRequest) (*VertoCredentials, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVertoCredentials not implemented")
}
func (UnimplementedVoiceServiceServer) StartChatCall(context.Context, *StartChatCallRequest) (*StartChatCallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartChatCall not implemented")
}
func (UnimplementedVoiceServiceServer) ScheduleConference(context.Context, *ScheduleConferenceRequest) (*Conference, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScheduleConference not implemented")
}
func (UnimplementedVoiceServiceServer) CreateAdHocFromChat(context.Context, *CreateAdHocFromChatRequest) (*Conference, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAdHocFromChat not implemented")
}
func (UnimplementedVoiceServiceServer) UpdateRSVP(context.Context, *UpdateRSVPRequest) (*Participant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRSVP not implemented")
}
func (UnimplementedVoiceServiceServer) UpdateParticipantRole(context.Context, *UpdateParticipantRoleRequest) (*Participant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParticipantRole not implemented")
}
func (UnimplementedVoiceServiceServer) AddParticipants(context.Context, *AddParticipantsRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddParticipants not implemented")
}
func (UnimplementedVoiceServiceServer) RemoveParticipant(context.Context, *RemoveParticipantRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveParticipant not implemented")
}
func (UnimplementedVoiceServiceServer) ListScheduledConferences(context.Context, *ListScheduledConferencesRequest) (*ListScheduledConferencesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListScheduledConferences not implemented")
}
func (UnimplementedVoiceServiceServer) GetChatConferences(context.Context, *GetChatConferencesRequest) (*GetChatConferencesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChatConferences not implemented")
}
func (UnimplementedVoiceServiceServer) CancelConference(context.Context, *CancelConferenceRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelConference not implemented")
}
func (UnimplementedVoiceServiceServer) GetConferenceHistory(context.Context, *GetConferenceHistoryRequest) (*ConferenceHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConferenceHistory not implemented")
}
func (UnimplementedVoiceServiceServer) ListChatConferenceHistory(context.Context, *ListChatConferenceHistoryRequest) (*ListChatConferenceHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChatConferenceHistory not implemented")
}
func (UnimplementedVoiceServiceServer) GetConferenceMessages(context.Context, *GetConferenceMessagesRequest) (*GetConferenceMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConferenceMessages not implemented")
}
func (UnimplementedVoiceServiceServer) GetModeratorActions(context.Context, *GetModeratorActionsRequest) (*GetModeratorActionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModeratorActions not implemented")
}
func (UnimplementedVoiceServiceServer) mustEmbedUnimplementedVoiceServiceServer() {}

// UnsafeVoiceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoiceServiceServer will
// result in compilation errors.
type UnsafeVoiceServiceServer interface {
	mustEmbedUnimplementedVoiceServiceServer()
}

func RegisterVoiceServiceServer(s grpc.ServiceRegistrar, srv VoiceServiceServer) {
	s.RegisterService(&VoiceService_ServiceDesc, srv)
}

func _VoiceService_CreateConference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).CreateConference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_CreateConference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).CreateConference(ctx, req.(*CreateConferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_GetConference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).GetConference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_GetConference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).GetConference(ctx, req.(*GetConferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_GetConferenceByFSName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConferenceByFSNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).GetConferenceByFSName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_GetConferenceByFSName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).GetConferenceByFSName(ctx, req.(*GetConferenceByFSNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_ListConferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConferencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).ListConferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_ListConferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).ListConferences(ctx, req.(*ListConferencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_ListAllActiveConferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).ListAllActiveConferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_ListAllActiveConferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).ListAllActiveConferences(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_EndConference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndConferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).EndConference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_EndConference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).EndConference(ctx, req.(*EndConferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_JoinConference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinConferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).JoinConference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_JoinConference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).JoinConference(ctx, req.(*JoinConferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_LeaveConference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveConferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).LeaveConference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_LeaveConference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).LeaveConference(ctx, req.(*LeaveConferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_GetParticipants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParticipantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).GetParticipants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_GetParticipants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).GetParticipants(ctx, req.(*GetParticipantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_MuteParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MuteParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).MuteParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_MuteParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).MuteParticipant(ctx, req.(*MuteParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_KickParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KickParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).KickParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_KickParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).KickParticipant(ctx, req.(*KickParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_InitiateCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).InitiateCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_InitiateCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).InitiateCall(ctx, req.(*InitiateCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_AnswerCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).AnswerCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_AnswerCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).AnswerCall(ctx, req.(*AnswerCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_HangupCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HangupCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).HangupCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_HangupCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).HangupCall(ctx, req.(*HangupCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_GetCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).GetCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_GetCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).GetCall(ctx, req.(*GetCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_GetCallHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCallHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).GetCallHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_GetCallHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).GetCallHistory(ctx, req.(*GetCallHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_GetVertoCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVertoCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).GetVertoCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_GetVertoCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).GetVertoCredentials(ctx, req.(*GetVertoCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_StartChatCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartChatCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).StartChatCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_StartChatCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).StartChatCall(ctx, req.(*StartChatCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_ScheduleConference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleConferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).ScheduleConference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_ScheduleConference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).ScheduleConference(ctx, req.(*ScheduleConferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_CreateAdHocFromChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAdHocFromChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).CreateAdHocFromChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_CreateAdHocFromChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).CreateAdHocFromChat(ctx, req.(*CreateAdHocFromChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_UpdateRSVP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRSVPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).UpdateRSVP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_UpdateRSVP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).UpdateRSVP(ctx, req.(*UpdateRSVPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_UpdateParticipantRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateParticipantRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).UpdateParticipantRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_UpdateParticipantRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).UpdateParticipantRole(ctx, req.(*UpdateParticipantRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_AddParticipants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddParticipantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).AddParticipants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_AddParticipants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).AddParticipants(ctx, req.(*AddParticipantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_RemoveParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).RemoveParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_RemoveParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).RemoveParticipant(ctx, req.(*RemoveParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_ListScheduledConferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScheduledConferencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).ListScheduledConferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_ListScheduledConferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).ListScheduledConferences(ctx, req.(*ListScheduledConferencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_GetChatConferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatConferencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).GetChatConferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_GetChatConferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).GetChatConferences(ctx, req.(*GetChatConferencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_CancelConference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelConferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).CancelConference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_CancelConference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).CancelConference(ctx, req.(*CancelConferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_GetConferenceHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConferenceHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).GetConferenceHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_GetConferenceHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).GetConferenceHistory(ctx, req.(*GetConferenceHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_ListChatConferenceHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChatConferenceHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).ListChatConferenceHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_ListChatConferenceHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).ListChatConferenceHistory(ctx, req.(*ListChatConferenceHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_GetConferenceMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConferenceMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).GetConferenceMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_GetConferenceMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).GetConferenceMessages(ctx, req.(*GetConferenceMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_GetModeratorActions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModeratorActionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).GetModeratorActions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_GetModeratorActions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).GetModeratorActions(ctx, req.(*GetModeratorActionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VoiceService_ServiceDesc is the grpc.ServiceDesc for VoiceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VoiceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voice.VoiceService",
	HandlerType: (*VoiceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateConference",
			Handler:    _VoiceService_CreateConference_Handler,
		},
		{
			MethodName: "GetConference",
			Handler:    _VoiceService_GetConference_Handler,
		},
		{
			MethodName: "GetConferenceByFSName",
			Handler:    _VoiceService_GetConferenceByFSName_Handler,
		},
		{
			MethodName: "ListConferences",
			Handler:    _VoiceService_ListConferences_Handler,
		},
		{
			MethodName: "ListAllActiveConferences",
			Handler:    _VoiceService_ListAllActiveConferences_Handler,
		},
		{
			MethodName: "EndConference",
			Handler:    _VoiceService_EndConference_Handler,
		},
		{
			MethodName: "JoinConference",
			Handler:    _VoiceService_JoinConference_Handler,
		},
		{
			MethodName: "LeaveConference",
			Handler:    _VoiceService_LeaveConference_Handler,
		},
		{
			MethodName: "GetParticipants",
			Handler:    _VoiceService_GetParticipants_Handler,
		},
		{
			MethodName: "MuteParticipant",
			Handler:    _VoiceService_MuteParticipant_Handler,
		},
		{
			MethodName: "KickParticipant",
			Handler:    _VoiceService_KickParticipant_Handler,
		},
		{
			MethodName: "InitiateCall",
			Handler:    _VoiceService_InitiateCall_Handler,
		},
		{
			MethodName: "AnswerCall",
			Handler:    _VoiceService_AnswerCall_Handler,
		},
		{
			MethodName: "HangupCall",
			Handler:    _VoiceService_HangupCall_Handler,
		},
		{
			MethodName: "GetCall",
			Handler:    _VoiceService_GetCall_Handler,
		},
		{
			MethodName: "GetCallHistory",
			Handler:    _VoiceService_GetCallHistory_Handler,
		},
		{
			MethodName: "GetVertoCredentials",
			Handler:    _VoiceService_GetVertoCredentials_Handler,
		},
		{
			MethodName: "StartChatCall",
			Handler:    _VoiceService_StartChatCall_Handler,
		},
		{
			MethodName: "ScheduleConference",
			Handler:    _VoiceService_ScheduleConference_Handler,
		},
		{
			MethodName: "CreateAdHocFromChat",
			Handler:    _VoiceService_CreateAdHocFromChat_Handler,
		},
		{
			MethodName: "UpdateRSVP",
			Handler:    _VoiceService_UpdateRSVP_Handler,
		},
		{
			MethodName: "UpdateParticipantRole",
			Handler:    _VoiceService_UpdateParticipantRole_Handler,
		},
		{
			MethodName: "AddParticipants",
			Handler:    _VoiceService_AddParticipants_Handler,
		},
		{
			MethodName: "RemoveParticipant",
			Handler:    _VoiceService_RemoveParticipant_Handler,
		},
		{
			MethodName: "ListScheduledConferences",
			Handler:    _VoiceService_ListScheduledConferences_Handler,
		},
		{
			MethodName: "GetChatConferences",
			Handler:    _VoiceService_GetChatConferences_Handler,
		},
		{
			MethodName: "CancelConference",
			Handler:    _VoiceService_CancelConference_Handler,
		},
		{
			MethodName: "GetConferenceHistory",
			Handler:    _VoiceService_GetConferenceHistory_Handler,
		},
		{
			MethodName: "ListChatConferenceHistory",
			Handler:    _VoiceService_ListChatConferenceHistory_Handler,
		},
		{
			MethodName: "GetConferenceMessages",
			Handler:    _VoiceService_GetConferenceMessages_Handler,
		},
		{
			MethodName: "GetModeratorActions",
			Handler:    _VoiceService_GetModeratorActions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/voice/voice.proto",
}
