// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: proto/files/files.proto

package files

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FilesServiceClient is the client API for FilesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FilesServiceClient interface {
	// Add a local file from server filesystem
	AddLocalFile(ctx context.Context, in *AddLocalFileRequest, opts ...grpc.CallOption) (*AddLocalFileResponse, error)
	// Create a new FileLink for an existing file (for message forwarding)
	CreateFileLink(ctx context.Context, in *CreateFileLinkRequest, opts ...grpc.CallOption) (*CreateFileLinkResponse, error)
	// Grant permissions to users for file links
	GrantPermissions(ctx context.Context, in *GrantPermissionsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Revoke permissions from a user for file links
	RevokePermissions(ctx context.Context, in *RevokePermissionsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Get file_id by link_id (for forward operation)
	GetFileIDByLinkID(ctx context.Context, in *GetFileIDByLinkIDRequest, opts ...grpc.CallOption) (*GetFileIDByLinkIDResponse, error)
	// Get file metadata by link IDs (batch)
	GetFilesByLinkIDs(ctx context.Context, in *GetFilesByLinkIDsRequest, opts ...grpc.CallOption) (*GetFilesByLinkIDsResponse, error)
}

type filesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFilesServiceClient(cc grpc.ClientConnInterface) FilesServiceClient {
	return &filesServiceClient{cc}
}

func (c *filesServiceClient) AddLocalFile(ctx context.Context, in *AddLocalFileRequest, opts ...grpc.CallOption) (*AddLocalFileResponse, error) {
	out := new(AddLocalFileResponse)
	err := c.cc.Invoke(ctx, "/files.FilesService/AddLocalFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesServiceClient) CreateFileLink(ctx context.Context, in *CreateFileLinkRequest, opts ...grpc.CallOption) (*CreateFileLinkResponse, error) {
	out := new(CreateFileLinkResponse)
	err := c.cc.Invoke(ctx, "/files.FilesService/CreateFileLink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesServiceClient) GrantPermissions(ctx context.Context, in *GrantPermissionsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/files.FilesService/GrantPermissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesServiceClient) RevokePermissions(ctx context.Context, in *RevokePermissionsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/files.FilesService/RevokePermissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesServiceClient) GetFileIDByLinkID(ctx context.Context, in *GetFileIDByLinkIDRequest, opts ...grpc.CallOption) (*GetFileIDByLinkIDResponse, error) {
	out := new(GetFileIDByLinkIDResponse)
	err := c.cc.Invoke(ctx, "/files.FilesService/GetFileIDByLinkID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesServiceClient) GetFilesByLinkIDs(ctx context.Context, in *GetFilesByLinkIDsRequest, opts ...grpc.CallOption) (*GetFilesByLinkIDsResponse, error) {
	out := new(GetFilesByLinkIDsResponse)
	err := c.cc.Invoke(ctx, "/files.FilesService/GetFilesByLinkIDs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FilesServiceServer is the server API for FilesService service.
// All implementations should embed UnimplementedFilesServiceServer
// for forward compatibility
type FilesServiceServer interface {
	// Add a local file from server filesystem
	AddLocalFile(context.Context, *AddLocalFileRequest) (*AddLocalFileResponse, error)
	// Create a new FileLink for an existing file (for message forwarding)
	CreateFileLink(context.Context, *CreateFileLinkRequest) (*CreateFileLinkResponse, error)
	// Grant permissions to users for file links
	GrantPermissions(context.Context, *GrantPermissionsRequest) (*emptypb.Empty, error)
	// Revoke permissions from a user for file links
	RevokePermissions(context.Context, *RevokePermissionsRequest) (*emptypb.Empty, error)
	// Get file_id by link_id (for forward operation)
	GetFileIDByLinkID(context.Context, *GetFileIDByLinkIDRequest) (*GetFileIDByLinkIDResponse, error)
	// Get file metadata by link IDs (batch)
	GetFilesByLinkIDs(context.Context, *GetFilesByLinkIDsRequest) (*GetFilesByLinkIDsResponse, error)
}

// UnimplementedFilesServiceServer should be embedded to have forward compatible implementations.
type UnimplementedFilesServiceServer struct {
}

func (UnimplementedFilesServiceServer) AddLocalFile(context.Context, *AddLocalFileRequest) (*AddLocalFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLocalFile not implemented")
}
func (UnimplementedFilesServiceServer) CreateFileLink(context.Context, *CreateFileLinkRequest) (*CreateFileLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFileLink not implemented")
}
func (UnimplementedFilesServiceServer) GrantPermissions(context.Context, *GrantPermissionsRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrantPermissions not implemented")
}
func (UnimplementedFilesServiceServer) RevokePermissions(context.Context, *RevokePermissionsRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokePermissions not implemented")
}
func (UnimplementedFilesServiceServer) GetFileIDByLinkID(context.Context, *GetFileIDByLinkIDRequest) (*GetFileIDByLinkIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileIDByLinkID not implemented")
}
func (UnimplementedFilesServiceServer) GetFilesByLinkIDs(context.Context, *GetFilesByLinkIDsRequest) (*GetFilesByLinkIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFilesByLinkIDs not implemented")
}

// UnsafeFilesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FilesServiceServer will
// result in compilation errors.
type UnsafeFilesServiceServer interface {
	mustEmbedUnimplementedFilesServiceServer()
}

func RegisterFilesServiceServer(s grpc.ServiceRegistrar, srv FilesServiceServer) {
	s.RegisterService(&FilesService_ServiceDesc, srv)
}

func _FilesService_AddLocalFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddLocalFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesServiceServer).AddLocalFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/files.FilesService/AddLocalFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesServiceServer).AddLocalFile(ctx, req.(*AddLocalFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesService_CreateFileLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFileLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesServiceServer).CreateFileLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/files.FilesService/CreateFileLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesServiceServer).CreateFileLink(ctx, req.(*CreateFileLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesService_GrantPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesServiceServer).GrantPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/files.FilesService/GrantPermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesServiceServer).GrantPermissions(ctx, req.(*GrantPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesService_RevokePermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokePermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesServiceServer).RevokePermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/files.FilesService/RevokePermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesServiceServer).RevokePermissions(ctx, req.(*RevokePermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesService_GetFileIDByLinkID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileIDByLinkIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesServiceServer).GetFileIDByLinkID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/files.FilesService/GetFileIDByLinkID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesServiceServer).GetFileIDByLinkID(ctx, req.(*GetFileIDByLinkIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesService_GetFilesByLinkIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFilesByLinkIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesServiceServer).GetFilesByLinkIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/files.FilesService/GetFilesByLinkIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesServiceServer).GetFilesByLinkIDs(ctx, req.(*GetFilesByLinkIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FilesService_ServiceDesc is the grpc.ServiceDesc for FilesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FilesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "files.FilesService",
	HandlerType: (*FilesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddLocalFile",
			Handler:    _FilesService_AddLocalFile_Handler,
		},
		{
			MethodName: "CreateFileLink",
			Handler:    _FilesService_CreateFileLink_Handler,
		},
		{
			MethodName: "GrantPermissions",
			Handler:    _FilesService_GrantPermissions_Handler,
		},
		{
			MethodName: "RevokePermissions",
			Handler:    _FilesService_RevokePermissions_Handler,
		},
		{
			MethodName: "GetFileIDByLinkID",
			Handler:    _FilesService_GetFileIDByLinkID_Handler,
		},
		{
			MethodName: "GetFilesByLinkIDs",
			Handler:    _FilesService_GetFilesByLinkIDs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/files/files.proto",
}
