// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.29.4
// source: proto/files/files.proto

package files

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AddLocalFile - add a file from server's local filesystem
type AddLocalFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerFilePath   string `protobuf:"bytes,1,opt,name=server_file_path,json=serverFilePath,proto3" json:"server_file_path,omitempty"`     // Path to file on server
	OriginalFilename string `protobuf:"bytes,2,opt,name=original_filename,json=originalFilename,proto3" json:"original_filename,omitempty"` // Original filename to store
	ContentType      string `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`                // MIME type (optional, will be detected if empty)
	UploadedBy       string `protobuf:"bytes,4,opt,name=uploaded_by,json=uploadedBy,proto3" json:"uploaded_by,omitempty"`                   // UUID of the user who owns the file
}

func (x *AddLocalFileRequest) Reset() {
	*x = AddLocalFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_files_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddLocalFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLocalFileRequest) ProtoMessage() {}

func (x *AddLocalFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLocalFileRequest.ProtoReflect.Descriptor instead.
func (*AddLocalFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{0}
}

func (x *AddLocalFileRequest) GetServerFilePath() string {
	if x != nil {
		return x.ServerFilePath
	}
	return ""
}

func (x *AddLocalFileRequest) GetOriginalFilename() string {
	if x != nil {
		return x.OriginalFilename
	}
	return ""
}

func (x *AddLocalFileRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *AddLocalFileRequest) GetUploadedBy() string {
	if x != nil {
		return x.UploadedBy
	}
	return ""
}

type AddLocalFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileId           string `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	LinkId           string `protobuf:"bytes,2,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	Filename         string `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	OriginalFilename string `protobuf:"bytes,4,opt,name=original_filename,json=originalFilename,proto3" json:"original_filename,omitempty"`
	ContentType      string `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Size             int64  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *AddLocalFileResponse) Reset() {
	*x = AddLocalFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_files_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddLocalFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLocalFileResponse) ProtoMessage() {}

func (x *AddLocalFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLocalFileResponse.ProtoReflect.Descriptor instead.
func (*AddLocalFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{1}
}

func (x *AddLocalFileResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *AddLocalFileResponse) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *AddLocalFileResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *AddLocalFileResponse) GetOriginalFilename() string {
	if x != nil {
		return x.OriginalFilename
	}
	return ""
}

func (x *AddLocalFileResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *AddLocalFileResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// CreateFileLink - create a new link for an existing file
type CreateFileLinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileId    string `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`          // ID of existing file
	CreatedBy string `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"` // UUID of user creating the link
}

func (x *CreateFileLinkRequest) Reset() {
	*x = CreateFileLinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_files_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFileLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileLinkRequest) ProtoMessage() {}

func (x *CreateFileLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateFileLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFileLinkRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *CreateFileLinkRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type CreateFileLinkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LinkId string `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	FileId string `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
}

func (x *CreateFileLinkResponse) Reset() {
	*x = CreateFileLinkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_files_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFileLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileLinkResponse) ProtoMessage() {}

func (x *CreateFileLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileLinkResponse.ProtoReflect.Descriptor instead.
func (*CreateFileLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFileLinkResponse) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *CreateFileLinkResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

// GrantPermissions - grant view/download permissions to users
type GrantPermissionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LinkIds   []string `protobuf:"bytes,1,rep,name=link_ids,json=linkIds,proto3" json:"link_ids,omitempty"`       // File link IDs
	UserIds   []string `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`       // User IDs to grant access
	GranterId string   `protobuf:"bytes,3,opt,name=granter_id,json=granterId,proto3" json:"granter_id,omitempty"` // User who grants permissions
}

func (x *GrantPermissionsRequest) Reset() {
	*x = GrantPermissionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_files_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrantPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantPermissionsRequest) ProtoMessage() {}

func (x *GrantPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantPermissionsRequest.ProtoReflect.Descriptor instead.
func (*GrantPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{4}
}

func (x *GrantPermissionsRequest) GetLinkIds() []string {
	if x != nil {
		return x.LinkIds
	}
	return nil
}

func (x *GrantPermissionsRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *GrantPermissionsRequest) GetGranterId() string {
	if x != nil {
		return x.GranterId
	}
	return ""
}

// RevokePermissions - revoke permissions from a user
type RevokePermissionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LinkIds []string `protobuf:"bytes,1,rep,name=link_ids,json=linkIds,proto3" json:"link_ids,omitempty"` // File link IDs
	UserId  string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`    // User ID to revoke from
}

func (x *RevokePermissionsRequest) Reset() {
	*x = RevokePermissionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_files_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevokePermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokePermissionsRequest) ProtoMessage() {}

func (x *RevokePermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokePermissionsRequest.ProtoReflect.Descriptor instead.
func (*RevokePermissionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{5}
}

func (x *RevokePermissionsRequest) GetLinkIds() []string {
	if x != nil {
		return x.LinkIds
	}
	return nil
}

func (x *RevokePermissionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetFileIDByLinkID - get file ID from link ID
type GetFileIDByLinkIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LinkId string `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
}

func (x *GetFileIDByLinkIDRequest) Reset() {
	*x = GetFileIDByLinkIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_files_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileIDByLinkIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileIDByLinkIDRequest) ProtoMessage() {}

func (x *GetFileIDByLinkIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileIDByLinkIDRequest.ProtoReflect.Descriptor instead.
func (*GetFileIDByLinkIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{6}
}

func (x *GetFileIDByLinkIDRequest) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

type GetFileIDByLinkIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileId string `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
}

func (x *GetFileIDByLinkIDResponse) Reset() {
	*x = GetFileIDByLinkIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_files_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileIDByLinkIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileIDByLinkIDResponse) ProtoMessage() {}

func (x *GetFileIDByLinkIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileIDByLinkIDResponse.ProtoReflect.Descriptor instead.
func (*GetFileIDByLinkIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{7}
}

func (x *GetFileIDByLinkIDResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

// GetFilesByLinkIDs - batch get file metadata
type GetFilesByLinkIDsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LinkIds []string `protobuf:"bytes,1,rep,name=link_ids,json=linkIds,proto3" json:"link_ids,omitempty"`
}

func (x *GetFilesByLinkIDsRequest) Reset() {
	*x = GetFilesByLinkIDsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_files_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFilesByLinkIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilesByLinkIDsRequest) ProtoMessage() {}

func (x *GetFilesByLinkIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilesByLinkIDsRequest.ProtoReflect.Descriptor instead.
func (*GetFilesByLinkIDsRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{8}
}

func (x *GetFilesByLinkIDsRequest) GetLinkIds() []string {
	if x != nil {
		return x.LinkIds
	}
	return nil
}

type FileAttachment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LinkId           string `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	FileId           string `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Filename         string `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	OriginalFilename string `protobuf:"bytes,4,opt,name=original_filename,json=originalFilename,proto3" json:"original_filename,omitempty"`
	ContentType      string `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Size             int64  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *FileAttachment) Reset() {
	*x = FileAttachment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_files_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileAttachment) ProtoMessage() {}

func (x *FileAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileAttachment.ProtoReflect.Descriptor instead.
func (*FileAttachment) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{9}
}

func (x *FileAttachment) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *FileAttachment) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileAttachment) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileAttachment) GetOriginalFilename() string {
	if x != nil {
		return x.OriginalFilename
	}
	return ""
}

func (x *FileAttachment) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *FileAttachment) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetFilesByLinkIDsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Files []*FileAttachment `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *GetFilesByLinkIDsResponse) Reset() {
	*x = GetFilesByLinkIDsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_files_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFilesByLinkIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilesByLinkIDsResponse) ProtoMessage() {}

func (x *GetFilesByLinkIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilesByLinkIDsResponse.ProtoReflect.Descriptor instead.
func (*GetFilesByLinkIDsResponse) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{10}
}

func (x *GetFilesByLinkIDsResponse) GetFiles() []*FileAttachment {
	if x != nil {
		return x.Files
	}
	return nil
}

// FileGroup represents a group with permissions
type FileGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CanRead     bool   `protobuf:"varint,3,opt,name=can_read,json=canRead,proto3" json:"can_read,omitempty"`
	CanDelete   bool   `protobuf:"varint,4,opt,name=can_delete,json=canDelete,proto3" json:"can_delete,omitempty"`
	CanTransfer bool   `protobuf:"varint,5,opt,name=can_transfer,json=canTransfer,proto3" json:"can_transfer,omitempty"`
}

func (x *FileGroup) Reset() {
	*x = FileGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_files_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileGroup) ProtoMessage() {}

func (x *FileGroup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileGroup.ProtoReflect.Descriptor instead.
func (*FileGroup) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{11}
}

func (x *FileGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileGroup) GetCanRead() bool {
	if x != nil {
		return x.CanRead
	}
	return false
}

func (x *FileGroup) GetCanDelete() bool {
	if x != nil {
		return x.CanDelete
	}
	return false
}

func (x *FileGroup) GetCanTransfer() bool {
	if x != nil {
		return x.CanTransfer
	}
	return false
}

// CreateFileGroup - create a new file group
type CreateFileGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CanRead     bool   `protobuf:"varint,2,opt,name=can_read,json=canRead,proto3" json:"can_read,omitempty"`
	CanDelete   bool   `protobuf:"varint,3,opt,name=can_delete,json=canDelete,proto3" json:"can_delete,omitempty"`
	CanTransfer bool   `protobuf:"varint,4,opt,name=can_transfer,json=canTransfer,proto3" json:"can_transfer,omitempty"`
}

func (x *CreateFileGroupRequest) Reset() {
	*x = CreateFileGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_files_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFileGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileGroupRequest) ProtoMessage() {}

func (x *CreateFileGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateFileGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{12}
}

func (x *CreateFileGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFileGroupRequest) GetCanRead() bool {
	if x != nil {
		return x.CanRead
	}
	return false
}

func (x *CreateFileGroupRequest) GetCanDelete() bool {
	if x != nil {
		return x.CanDelete
	}
	return false
}

func (x *CreateFileGroupRequest) GetCanTransfer() bool {
	if x != nil {
		return x.CanTransfer
	}
	return false
}

type CreateFileGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group *FileGroup `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
}

func (x *CreateFileGroupResponse) Reset() {
	*x = CreateFileGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_files_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFileGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileGroupResponse) ProtoMessage() {}

func (x *CreateFileGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateFileGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{13}
}

func (x *CreateFileGroupResponse) GetGroup() *FileGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

// DeleteFileGroup - delete a file group
type DeleteFileGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
}

func (x *DeleteFileGroupRequest) Reset() {
	*x = DeleteFileGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_files_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFileGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileGroupRequest) ProtoMessage() {}

func (x *DeleteFileGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteFileGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

// AddUserToGroup - add user to a group
type AddUserToGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId  string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *AddUserToGroupRequest) Reset() {
	*x = AddUserToGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_files_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddUserToGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserToGroupRequest) ProtoMessage() {}

func (x *AddUserToGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserToGroupRequest.ProtoReflect.Descriptor instead.
func (*AddUserToGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{15}
}

func (x *AddUserToGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *AddUserToGroupRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// RemoveUserFromGroup - remove user from a group
type RemoveUserFromGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId  string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *RemoveUserFromGroupRequest) Reset() {
	*x = RemoveUserFromGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_files_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveUserFromGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserFromGroupRequest) ProtoMessage() {}

func (x *RemoveUserFromGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserFromGroupRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserFromGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveUserFromGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *RemoveUserFromGroupRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// AddFileLinkToGroups - associate file link with groups
type AddFileLinkToGroupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileLinkId string   `protobuf:"bytes,1,opt,name=file_link_id,json=fileLinkId,proto3" json:"file_link_id,omitempty"`
	GroupIds   []string `protobuf:"bytes,2,rep,name=group_ids,json=groupIds,proto3" json:"group_ids,omitempty"`
}

func (x *AddFileLinkToGroupsRequest) Reset() {
	*x = AddFileLinkToGroupsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_files_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddFileLinkToGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFileLinkToGroupsRequest) ProtoMessage() {}

func (x *AddFileLinkToGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFileLinkToGroupsRequest.ProtoReflect.Descriptor instead.
func (*AddFileLinkToGroupsRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{17}
}

func (x *AddFileLinkToGroupsRequest) GetFileLinkId() string {
	if x != nil {
		return x.FileLinkId
	}
	return ""
}

func (x *AddFileLinkToGroupsRequest) GetGroupIds() []string {
	if x != nil {
		return x.GroupIds
	}
	return nil
}

// GetFilesByGroup - get all files in a group
type GetFilesByGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
}

func (x *GetFilesByGroupRequest) Reset() {
	*x = GetFilesByGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_files_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFilesByGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilesByGroupRequest) ProtoMessage() {}

func (x *GetFilesByGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilesByGroupRequest.ProtoReflect.Descriptor instead.
func (*GetFilesByGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{18}
}

func (x *GetFilesByGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type FileLinkInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FileId     string `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	UploadedBy string `protobuf:"bytes,3,opt,name=uploaded_by,json=uploadedBy,proto3" json:"uploaded_by,omitempty"`
}

func (x *FileLinkInfo) Reset() {
	*x = FileLinkInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_files_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileLinkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileLinkInfo) ProtoMessage() {}

func (x *FileLinkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileLinkInfo.ProtoReflect.Descriptor instead.
func (*FileLinkInfo) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{19}
}

func (x *FileLinkInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileLinkInfo) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileLinkInfo) GetUploadedBy() string {
	if x != nil {
		return x.UploadedBy
	}
	return ""
}

type GetFilesByGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileLinks []*FileLinkInfo `protobuf:"bytes,1,rep,name=file_links,json=fileLinks,proto3" json:"file_links,omitempty"`
}

func (x *GetFilesByGroupResponse) Reset() {
	*x = GetFilesByGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_files_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFilesByGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilesByGroupResponse) ProtoMessage() {}

func (x *GetFilesByGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilesByGroupResponse.ProtoReflect.Descriptor instead.
func (*GetFilesByGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{20}
}

func (x *GetFilesByGroupResponse) GetFileLinks() []*FileLinkInfo {
	if x != nil {
		return x.FileLinks
	}
	return nil
}

// RemoveUserFromAllGroupFiles - remove user from multiple groups
type RemoveUserFromAllGroupFilesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupIds []string `protobuf:"bytes,1,rep,name=group_ids,json=groupIds,proto3" json:"group_ids,omitempty"`
	UserId   string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *RemoveUserFromAllGroupFilesRequest) Reset() {
	*x = RemoveUserFromAllGroupFilesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_files_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveUserFromAllGroupFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserFromAllGroupFilesRequest) ProtoMessage() {}

func (x *RemoveUserFromAllGroupFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserFromAllGroupFilesRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserFromAllGroupFilesRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{21}
}

func (x *RemoveUserFromAllGroupFilesRequest) GetGroupIds() []string {
	if x != nil {
		return x.GroupIds
	}
	return nil
}

func (x *RemoveUserFromAllGroupFilesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_proto_files_files_proto protoreflect.FileDescriptor

var file_proto_files_files_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb0, 0x01,
	0x0a, 0x13, 0x41, 0x64, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x10, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f,
	0x66, 0x69, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12,
	0x2b, 0x0a, 0x11, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x66, 0x69, 0x6c, 0x65,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x61, 0x6c, 0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x42, 0x79,
	0x22, 0xc8, 0x01, 0x0a, 0x14, 0x41, 0x64, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x6c,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65,
	0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x69, 0x6e, 0x6b, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66,
	0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66,
	0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x6f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x61, 0x6c, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x10, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x46, 0x69, 0x6c, 0x65,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x4f, 0x0a, 0x15, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x22, 0x4a, 0x0a, 0x16,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x69, 0x6e, 0x6b, 0x49, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x6e, 0x0a, 0x17, 0x47, 0x72, 0x61, 0x6e,
	0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x69, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x69, 0x6e, 0x6b, 0x49, 0x64, 0x73, 0x12, 0x19,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x72, 0x61,
	0x6e, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67,
	0x72, 0x61, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22, 0x4e, 0x0a, 0x18, 0x52, 0x65, 0x76, 0x6f,
	0x6b, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x69, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x69, 0x6e, 0x6b, 0x49, 0x64, 0x73, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x33, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x46,
	0x69, 0x6c, 0x65, 0x49, 0x44, 0x42, 0x79, 0x4c, 0x69, 0x6e, 0x6b, 0x49, 0x44, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x69, 0x6e, 0x6b, 0x49, 0x64, 0x22, 0x34, 0x0a,
	0x19, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x44, 0x42, 0x79, 0x4c, 0x69, 0x6e, 0x6b,
	0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69,
	0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c,
	0x65, 0x49, 0x64, 0x22, 0x35, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x42,
	0x79, 0x4c, 0x69, 0x6e, 0x6b, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x19, 0x0a, 0x08, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x07, 0x6c, 0x69, 0x6e, 0x6b, 0x49, 0x64, 0x73, 0x22, 0xc2, 0x01, 0x0a, 0x0e, 0x46,
	0x69, 0x6c, 0x65, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6c, 0x69, 0x6e, 0x6b, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x6f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c,
	0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22,
	0x48, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x42, 0x79, 0x4c, 0x69, 0x6e,
	0x6b, 0x49, 0x44, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x05,
	0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x8c, 0x01, 0x0a, 0x09, 0x46, 0x69,
	0x6c, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x63,
	0x61, 0x6e, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63,
	0x61, 0x6e, 0x52, 0x65, 0x61, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x6e, 0x5f, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x63, 0x61, 0x6e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x61, 0x6e, 0x5f, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x63, 0x61, 0x6e,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x22, 0x89, 0x01, 0x0a, 0x16, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x61, 0x6e, 0x5f, 0x72,
	0x65, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63, 0x61, 0x6e, 0x52, 0x65,
	0x61, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x6e, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x63, 0x61, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x61, 0x6e, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x63, 0x61, 0x6e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x22, 0x41, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x26, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x22, 0x33, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x46, 0x69, 0x6c, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x4b, 0x0a, 0x15,
	0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x50, 0x0a, 0x1a, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x46, 0x72, 0x6f, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x5b, 0x0a, 0x1a, 0x41,
	0x64, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x6f, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0c, 0x66, 0x69, 0x6c,
	0x65, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x66, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x73, 0x22, 0x33, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x46,
	0x69, 0x6c, 0x65, 0x73, 0x42, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x58, 0x0a,
	0x0c, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x65, 0x64, 0x42, 0x79, 0x22, 0x4d, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x46, 0x69,
	0x6c, 0x65, 0x73, 0x42, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x32, 0x0a, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x66, 0x69, 0x6c,
	0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x22, 0x5a, 0x0a, 0x22, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x32, 0xac, 0x08, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x46,
	0x69, 0x6c, 0x65, 0x12, 0x1a, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x4c,
	0x6f, 0x63, 0x61, 0x6c, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x6c,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x0e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x1c,
	0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c,
	0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x4c,
	0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x10, 0x47,
	0x72, 0x61, 0x6e, 0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x1e, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x50, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x4c, 0x0a, 0x11, 0x52, 0x65, 0x76, 0x6f, 0x6b,
	0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1f, 0x2e, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x56, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65,
	0x49, 0x44, 0x42, 0x79, 0x4c, 0x69, 0x6e, 0x6b, 0x49, 0x44, 0x12, 0x1f, 0x2e, 0x66, 0x69, 0x6c,
	0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x44, 0x42, 0x79, 0x4c, 0x69,
	0x6e, 0x6b, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x44, 0x42, 0x79, 0x4c,
	0x69, 0x6e, 0x6b, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x42, 0x79, 0x4c, 0x69, 0x6e, 0x6b, 0x49,
	0x44, 0x73, 0x12, 0x1f, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69,
	0x6c, 0x65, 0x73, 0x42, 0x79, 0x4c, 0x69, 0x6e, 0x6b, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x46,
	0x69, 0x6c, 0x65, 0x73, 0x42, 0x79, 0x4c, 0x69, 0x6e, 0x6b, 0x49, 0x44, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46,
	0x69, 0x6c, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1d, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x46, 0x69, 0x6c, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1d, 0x2e, 0x66, 0x69, 0x6c,
	0x65, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x12, 0x46, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x12, 0x1c, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x55,
	0x73, 0x65, 0x72, 0x54, 0x6f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x50, 0x0a, 0x13, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x46, 0x72, 0x6f, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x12, 0x21, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x46, 0x72, 0x6f, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x50, 0x0a, 0x13, 0x41,
	0x64, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x6f, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x73, 0x12, 0x21, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x46, 0x69,
	0x6c, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x6f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x50, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x42, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x12, 0x1d, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65,
	0x73, 0x42, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73,
	0x42, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x60, 0x0a, 0x1b, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x46, 0x72, 0x6f,
	0x6d, 0x41, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x29,
	0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x46, 0x69, 0x6c,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x69, 0x63, 0x65, 0x67, 0x72, 0x65, 0x67, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x2d, 0x73, 0x6d, 0x70,
	0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_files_files_proto_rawDescOnce sync.Once
	file_proto_files_files_proto_rawDescData = file_proto_files_files_proto_rawDesc
)

func file_proto_files_files_proto_rawDescGZIP() []byte {
	file_proto_files_files_proto_rawDescOnce.Do(func() {
		file_proto_files_files_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_files_files_proto_rawDescData)
	})
	return file_proto_files_files_proto_rawDescData
}

var file_proto_files_files_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_files_files_proto_goTypes = []any{
	(*AddLocalFileRequest)(nil),                // 0: files.AddLocalFileRequest
	(*AddLocalFileResponse)(nil),               // 1: files.AddLocalFileResponse
	(*CreateFileLinkRequest)(nil),              // 2: files.CreateFileLinkRequest
	(*CreateFileLinkResponse)(nil),             // 3: files.CreateFileLinkResponse
	(*GrantPermissionsRequest)(nil),            // 4: files.GrantPermissionsRequest
	(*RevokePermissionsRequest)(nil),           // 5: files.RevokePermissionsRequest
	(*GetFileIDByLinkIDRequest)(nil),           // 6: files.GetFileIDByLinkIDRequest
	(*GetFileIDByLinkIDResponse)(nil),          // 7: files.GetFileIDByLinkIDResponse
	(*GetFilesByLinkIDsRequest)(nil),           // 8: files.GetFilesByLinkIDsRequest
	(*FileAttachment)(nil),                     // 9: files.FileAttachment
	(*GetFilesByLinkIDsResponse)(nil),          // 10: files.GetFilesByLinkIDsResponse
	(*FileGroup)(nil),                          // 11: files.FileGroup
	(*CreateFileGroupRequest)(nil),             // 12: files.CreateFileGroupRequest
	(*CreateFileGroupResponse)(nil),            // 13: files.CreateFileGroupResponse
	(*DeleteFileGroupRequest)(nil),             // 14: files.DeleteFileGroupRequest
	(*AddUserToGroupRequest)(nil),              // 15: files.AddUserToGroupRequest
	(*RemoveUserFromGroupRequest)(nil),         // 16: files.RemoveUserFromGroupRequest
	(*AddFileLinkToGroupsRequest)(nil),         // 17: files.AddFileLinkToGroupsRequest
	(*GetFilesByGroupRequest)(nil),             // 18: files.GetFilesByGroupRequest
	(*FileLinkInfo)(nil),                       // 19: files.FileLinkInfo
	(*GetFilesByGroupResponse)(nil),            // 20: files.GetFilesByGroupResponse
	(*RemoveUserFromAllGroupFilesRequest)(nil), // 21: files.RemoveUserFromAllGroupFilesRequest
	(*emptypb.Empty)(nil),                      // 22: google.protobuf.Empty
}
var file_proto_files_files_proto_depIdxs = []int32{
	9,  // 0: files.GetFilesByLinkIDsResponse.files:type_name -> files.FileAttachment
	11, // 1: files.CreateFileGroupResponse.group:type_name -> files.FileGroup
	19, // 2: files.GetFilesByGroupResponse.file_links:type_name -> files.FileLinkInfo
	0,  // 3: files.FilesService.AddLocalFile:input_type -> files.AddLocalFileRequest
	2,  // 4: files.FilesService.CreateFileLink:input_type -> files.CreateFileLinkRequest
	4,  // 5: files.FilesService.GrantPermissions:input_type -> files.GrantPermissionsRequest
	5,  // 6: files.FilesService.RevokePermissions:input_type -> files.RevokePermissionsRequest
	6,  // 7: files.FilesService.GetFileIDByLinkID:input_type -> files.GetFileIDByLinkIDRequest
	8,  // 8: files.FilesService.GetFilesByLinkIDs:input_type -> files.GetFilesByLinkIDsRequest
	12, // 9: files.FilesService.CreateFileGroup:input_type -> files.CreateFileGroupRequest
	14, // 10: files.FilesService.DeleteFileGroup:input_type -> files.DeleteFileGroupRequest
	15, // 11: files.FilesService.AddUserToGroup:input_type -> files.AddUserToGroupRequest
	16, // 12: files.FilesService.RemoveUserFromGroup:input_type -> files.RemoveUserFromGroupRequest
	17, // 13: files.FilesService.AddFileLinkToGroups:input_type -> files.AddFileLinkToGroupsRequest
	18, // 14: files.FilesService.GetFilesByGroup:input_type -> files.GetFilesByGroupRequest
	21, // 15: files.FilesService.RemoveUserFromAllGroupFiles:input_type -> files.RemoveUserFromAllGroupFilesRequest
	1,  // 16: files.FilesService.AddLocalFile:output_type -> files.AddLocalFileResponse
	3,  // 17: files.FilesService.CreateFileLink:output_type -> files.CreateFileLinkResponse
	22, // 18: files.FilesService.GrantPermissions:output_type -> google.protobuf.Empty
	22, // 19: files.FilesService.RevokePermissions:output_type -> google.protobuf.Empty
	7,  // 20: files.FilesService.GetFileIDByLinkID:output_type -> files.GetFileIDByLinkIDResponse
	10, // 21: files.FilesService.GetFilesByLinkIDs:output_type -> files.GetFilesByLinkIDsResponse
	13, // 22: files.FilesService.CreateFileGroup:output_type -> files.CreateFileGroupResponse
	22, // 23: files.FilesService.DeleteFileGroup:output_type -> google.protobuf.Empty
	22, // 24: files.FilesService.AddUserToGroup:output_type -> google.protobuf.Empty
	22, // 25: files.FilesService.RemoveUserFromGroup:output_type -> google.protobuf.Empty
	22, // 26: files.FilesService.AddFileLinkToGroups:output_type -> google.protobuf.Empty
	20, // 27: files.FilesService.GetFilesByGroup:output_type -> files.GetFilesByGroupResponse
	22, // 28: files.FilesService.RemoveUserFromAllGroupFiles:output_type -> google.protobuf.Empty
	16, // [16:29] is the sub-list for method output_type
	3,  // [3:16] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_files_files_proto_init() }
func file_proto_files_files_proto_init() {
	if File_proto_files_files_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_files_files_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AddLocalFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_files_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AddLocalFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_files_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CreateFileLinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_files_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CreateFileLinkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_files_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GrantPermissionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_files_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*RevokePermissionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_files_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetFileIDByLinkIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_files_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetFileIDByLinkIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_files_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GetFilesByLinkIDsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_files_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*FileAttachment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_files_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*GetFilesByLinkIDsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_files_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*FileGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_files_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*CreateFileGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_files_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*CreateFileGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_files_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteFileGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_files_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*AddUserToGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_files_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*RemoveUserFromGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_files_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*AddFileLinkToGroupsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_files_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*GetFilesByGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_files_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*FileLinkInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_files_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*GetFilesByGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_files_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*RemoveUserFromAllGroupFilesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_files_files_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_files_files_proto_goTypes,
		DependencyIndexes: file_proto_files_files_proto_depIdxs,
		MessageInfos:      file_proto_files_files_proto_msgTypes,
	}.Build()
	File_proto_files_files_proto = out.File
	file_proto_files_files_proto_rawDesc = nil
	file_proto_files_files_proto_goTypes = nil
	file_proto_files_files_proto_depIdxs = nil
}
