// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/files/files.proto

package files

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AddLocalFile - add a file from server's local filesystem
type AddLocalFileRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServerFilePath   string                 `protobuf:"bytes,1,opt,name=server_file_path,json=serverFilePath,proto3" json:"server_file_path,omitempty"`     // Path to file on server
	OriginalFilename string                 `protobuf:"bytes,2,opt,name=original_filename,json=originalFilename,proto3" json:"original_filename,omitempty"` // Original filename to store
	ContentType      string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`                // MIME type (optional, will be detected if empty)
	UploadedBy       string                 `protobuf:"bytes,4,opt,name=uploaded_by,json=uploadedBy,proto3" json:"uploaded_by,omitempty"`                   // UUID of the user who owns the file
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AddLocalFileRequest) Reset() {
	*x = AddLocalFileRequest{}
	mi := &file_proto_files_files_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddLocalFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLocalFileRequest) ProtoMessage() {}

func (x *AddLocalFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLocalFileRequest.ProtoReflect.Descriptor instead.
func (*AddLocalFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{0}
}

func (x *AddLocalFileRequest) GetServerFilePath() string {
	if x != nil {
		return x.ServerFilePath
	}
	return ""
}

func (x *AddLocalFileRequest) GetOriginalFilename() string {
	if x != nil {
		return x.OriginalFilename
	}
	return ""
}

func (x *AddLocalFileRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *AddLocalFileRequest) GetUploadedBy() string {
	if x != nil {
		return x.UploadedBy
	}
	return ""
}

type AddLocalFileResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FileId           string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	LinkId           string                 `protobuf:"bytes,2,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	Filename         string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	OriginalFilename string                 `protobuf:"bytes,4,opt,name=original_filename,json=originalFilename,proto3" json:"original_filename,omitempty"`
	ContentType      string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Size             int64                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AddLocalFileResponse) Reset() {
	*x = AddLocalFileResponse{}
	mi := &file_proto_files_files_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddLocalFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLocalFileResponse) ProtoMessage() {}

func (x *AddLocalFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLocalFileResponse.ProtoReflect.Descriptor instead.
func (*AddLocalFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{1}
}

func (x *AddLocalFileResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *AddLocalFileResponse) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *AddLocalFileResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *AddLocalFileResponse) GetOriginalFilename() string {
	if x != nil {
		return x.OriginalFilename
	}
	return ""
}

func (x *AddLocalFileResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *AddLocalFileResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// CreateFileLink - create a new link for an existing file
type CreateFileLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`          // ID of existing file
	CreatedBy     string                 `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"` // UUID of user creating the link
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileLinkRequest) Reset() {
	*x = CreateFileLinkRequest{}
	mi := &file_proto_files_files_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileLinkRequest) ProtoMessage() {}

func (x *CreateFileLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateFileLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFileLinkRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *CreateFileLinkRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type CreateFileLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkId        string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileLinkResponse) Reset() {
	*x = CreateFileLinkResponse{}
	mi := &file_proto_files_files_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileLinkResponse) ProtoMessage() {}

func (x *CreateFileLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileLinkResponse.ProtoReflect.Descriptor instead.
func (*CreateFileLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFileLinkResponse) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *CreateFileLinkResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

// GrantPermissions - grant view/download permissions to users
type GrantPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkIds       []string               `protobuf:"bytes,1,rep,name=link_ids,json=linkIds,proto3" json:"link_ids,omitempty"`       // File link IDs
	UserIds       []string               `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`       // User IDs to grant access
	GranterId     string                 `protobuf:"bytes,3,opt,name=granter_id,json=granterId,proto3" json:"granter_id,omitempty"` // User who grants permissions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantPermissionsRequest) Reset() {
	*x = GrantPermissionsRequest{}
	mi := &file_proto_files_files_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantPermissionsRequest) ProtoMessage() {}

func (x *GrantPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantPermissionsRequest.ProtoReflect.Descriptor instead.
func (*GrantPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{4}
}

func (x *GrantPermissionsRequest) GetLinkIds() []string {
	if x != nil {
		return x.LinkIds
	}
	return nil
}

func (x *GrantPermissionsRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *GrantPermissionsRequest) GetGranterId() string {
	if x != nil {
		return x.GranterId
	}
	return ""
}

// RevokePermissions - revoke permissions from a user
type RevokePermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkIds       []string               `protobuf:"bytes,1,rep,name=link_ids,json=linkIds,proto3" json:"link_ids,omitempty"` // File link IDs
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`    // User ID to revoke from
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokePermissionsRequest) Reset() {
	*x = RevokePermissionsRequest{}
	mi := &file_proto_files_files_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokePermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokePermissionsRequest) ProtoMessage() {}

func (x *RevokePermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokePermissionsRequest.ProtoReflect.Descriptor instead.
func (*RevokePermissionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{5}
}

func (x *RevokePermissionsRequest) GetLinkIds() []string {
	if x != nil {
		return x.LinkIds
	}
	return nil
}

func (x *RevokePermissionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetFileIDByLinkID - get file ID from link ID
type GetFileIDByLinkIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkId        string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileIDByLinkIDRequest) Reset() {
	*x = GetFileIDByLinkIDRequest{}
	mi := &file_proto_files_files_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileIDByLinkIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileIDByLinkIDRequest) ProtoMessage() {}

func (x *GetFileIDByLinkIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileIDByLinkIDRequest.ProtoReflect.Descriptor instead.
func (*GetFileIDByLinkIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{6}
}

func (x *GetFileIDByLinkIDRequest) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

type GetFileIDByLinkIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileIDByLinkIDResponse) Reset() {
	*x = GetFileIDByLinkIDResponse{}
	mi := &file_proto_files_files_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileIDByLinkIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileIDByLinkIDResponse) ProtoMessage() {}

func (x *GetFileIDByLinkIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileIDByLinkIDResponse.ProtoReflect.Descriptor instead.
func (*GetFileIDByLinkIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{7}
}

func (x *GetFileIDByLinkIDResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

// GetFilesByLinkIDs - batch get file metadata
type GetFilesByLinkIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkIds       []string               `protobuf:"bytes,1,rep,name=link_ids,json=linkIds,proto3" json:"link_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilesByLinkIDsRequest) Reset() {
	*x = GetFilesByLinkIDsRequest{}
	mi := &file_proto_files_files_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilesByLinkIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilesByLinkIDsRequest) ProtoMessage() {}

func (x *GetFilesByLinkIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilesByLinkIDsRequest.ProtoReflect.Descriptor instead.
func (*GetFilesByLinkIDsRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{8}
}

func (x *GetFilesByLinkIDsRequest) GetLinkIds() []string {
	if x != nil {
		return x.LinkIds
	}
	return nil
}

type FileAttachment struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LinkId           string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	FileId           string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Filename         string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	OriginalFilename string                 `protobuf:"bytes,4,opt,name=original_filename,json=originalFilename,proto3" json:"original_filename,omitempty"`
	ContentType      string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Size             int64                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FileAttachment) Reset() {
	*x = FileAttachment{}
	mi := &file_proto_files_files_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileAttachment) ProtoMessage() {}

func (x *FileAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileAttachment.ProtoReflect.Descriptor instead.
func (*FileAttachment) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{9}
}

func (x *FileAttachment) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *FileAttachment) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileAttachment) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileAttachment) GetOriginalFilename() string {
	if x != nil {
		return x.OriginalFilename
	}
	return ""
}

func (x *FileAttachment) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *FileAttachment) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetFilesByLinkIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileAttachment      `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilesByLinkIDsResponse) Reset() {
	*x = GetFilesByLinkIDsResponse{}
	mi := &file_proto_files_files_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilesByLinkIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilesByLinkIDsResponse) ProtoMessage() {}

func (x *GetFilesByLinkIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilesByLinkIDsResponse.ProtoReflect.Descriptor instead.
func (*GetFilesByLinkIDsResponse) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{10}
}

func (x *GetFilesByLinkIDsResponse) GetFiles() []*FileAttachment {
	if x != nil {
		return x.Files
	}
	return nil
}

// FileGroup represents a group with permissions
type FileGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CanRead       bool                   `protobuf:"varint,3,opt,name=can_read,json=canRead,proto3" json:"can_read,omitempty"`
	CanDelete     bool                   `protobuf:"varint,4,opt,name=can_delete,json=canDelete,proto3" json:"can_delete,omitempty"`
	CanTransfer   bool                   `protobuf:"varint,5,opt,name=can_transfer,json=canTransfer,proto3" json:"can_transfer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileGroup) Reset() {
	*x = FileGroup{}
	mi := &file_proto_files_files_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileGroup) ProtoMessage() {}

func (x *FileGroup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileGroup.ProtoReflect.Descriptor instead.
func (*FileGroup) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{11}
}

func (x *FileGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileGroup) GetCanRead() bool {
	if x != nil {
		return x.CanRead
	}
	return false
}

func (x *FileGroup) GetCanDelete() bool {
	if x != nil {
		return x.CanDelete
	}
	return false
}

func (x *FileGroup) GetCanTransfer() bool {
	if x != nil {
		return x.CanTransfer
	}
	return false
}

// CreateFileGroup - create a new file group
type CreateFileGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CanRead       bool                   `protobuf:"varint,2,opt,name=can_read,json=canRead,proto3" json:"can_read,omitempty"`
	CanDelete     bool                   `protobuf:"varint,3,opt,name=can_delete,json=canDelete,proto3" json:"can_delete,omitempty"`
	CanTransfer   bool                   `protobuf:"varint,4,opt,name=can_transfer,json=canTransfer,proto3" json:"can_transfer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileGroupRequest) Reset() {
	*x = CreateFileGroupRequest{}
	mi := &file_proto_files_files_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileGroupRequest) ProtoMessage() {}

func (x *CreateFileGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateFileGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{12}
}

func (x *CreateFileGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFileGroupRequest) GetCanRead() bool {
	if x != nil {
		return x.CanRead
	}
	return false
}

func (x *CreateFileGroupRequest) GetCanDelete() bool {
	if x != nil {
		return x.CanDelete
	}
	return false
}

func (x *CreateFileGroupRequest) GetCanTransfer() bool {
	if x != nil {
		return x.CanTransfer
	}
	return false
}

type CreateFileGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *FileGroup             `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileGroupResponse) Reset() {
	*x = CreateFileGroupResponse{}
	mi := &file_proto_files_files_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileGroupResponse) ProtoMessage() {}

func (x *CreateFileGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateFileGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{13}
}

func (x *CreateFileGroupResponse) GetGroup() *FileGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

// DeleteFileGroup - delete a file group
type DeleteFileGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileGroupRequest) Reset() {
	*x = DeleteFileGroupRequest{}
	mi := &file_proto_files_files_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileGroupRequest) ProtoMessage() {}

func (x *DeleteFileGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteFileGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

// AddUserToGroup - add user to a group
type AddUserToGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserToGroupRequest) Reset() {
	*x = AddUserToGroupRequest{}
	mi := &file_proto_files_files_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserToGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserToGroupRequest) ProtoMessage() {}

func (x *AddUserToGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserToGroupRequest.ProtoReflect.Descriptor instead.
func (*AddUserToGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{15}
}

func (x *AddUserToGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *AddUserToGroupRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// RemoveUserFromGroup - remove user from a group
type RemoveUserFromGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserFromGroupRequest) Reset() {
	*x = RemoveUserFromGroupRequest{}
	mi := &file_proto_files_files_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserFromGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserFromGroupRequest) ProtoMessage() {}

func (x *RemoveUserFromGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserFromGroupRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserFromGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveUserFromGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *RemoveUserFromGroupRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// AddFileLinkToGroups - associate file link with groups
type AddFileLinkToGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileLinkId    string                 `protobuf:"bytes,1,opt,name=file_link_id,json=fileLinkId,proto3" json:"file_link_id,omitempty"`
	GroupIds      []string               `protobuf:"bytes,2,rep,name=group_ids,json=groupIds,proto3" json:"group_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFileLinkToGroupsRequest) Reset() {
	*x = AddFileLinkToGroupsRequest{}
	mi := &file_proto_files_files_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFileLinkToGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFileLinkToGroupsRequest) ProtoMessage() {}

func (x *AddFileLinkToGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFileLinkToGroupsRequest.ProtoReflect.Descriptor instead.
func (*AddFileLinkToGroupsRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{17}
}

func (x *AddFileLinkToGroupsRequest) GetFileLinkId() string {
	if x != nil {
		return x.FileLinkId
	}
	return ""
}

func (x *AddFileLinkToGroupsRequest) GetGroupIds() []string {
	if x != nil {
		return x.GroupIds
	}
	return nil
}

// GetFilesByGroup - get all files in a group
type GetFilesByGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilesByGroupRequest) Reset() {
	*x = GetFilesByGroupRequest{}
	mi := &file_proto_files_files_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilesByGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilesByGroupRequest) ProtoMessage() {}

func (x *GetFilesByGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilesByGroupRequest.ProtoReflect.Descriptor instead.
func (*GetFilesByGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{18}
}

func (x *GetFilesByGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type FileLinkInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	UploadedBy    string                 `protobuf:"bytes,3,opt,name=uploaded_by,json=uploadedBy,proto3" json:"uploaded_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileLinkInfo) Reset() {
	*x = FileLinkInfo{}
	mi := &file_proto_files_files_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileLinkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileLinkInfo) ProtoMessage() {}

func (x *FileLinkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileLinkInfo.ProtoReflect.Descriptor instead.
func (*FileLinkInfo) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{19}
}

func (x *FileLinkInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileLinkInfo) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileLinkInfo) GetUploadedBy() string {
	if x != nil {
		return x.UploadedBy
	}
	return ""
}

type GetFilesByGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileLinks     []*FileLinkInfo        `protobuf:"bytes,1,rep,name=file_links,json=fileLinks,proto3" json:"file_links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilesByGroupResponse) Reset() {
	*x = GetFilesByGroupResponse{}
	mi := &file_proto_files_files_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilesByGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilesByGroupResponse) ProtoMessage() {}

func (x *GetFilesByGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilesByGroupResponse.ProtoReflect.Descriptor instead.
func (*GetFilesByGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{20}
}

func (x *GetFilesByGroupResponse) GetFileLinks() []*FileLinkInfo {
	if x != nil {
		return x.FileLinks
	}
	return nil
}

// RemoveUserFromAllGroupFiles - remove user from multiple groups
type RemoveUserFromAllGroupFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupIds      []string               `protobuf:"bytes,1,rep,name=group_ids,json=groupIds,proto3" json:"group_ids,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserFromAllGroupFilesRequest) Reset() {
	*x = RemoveUserFromAllGroupFilesRequest{}
	mi := &file_proto_files_files_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserFromAllGroupFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserFromAllGroupFilesRequest) ProtoMessage() {}

func (x *RemoveUserFromAllGroupFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserFromAllGroupFilesRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserFromAllGroupFilesRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{21}
}

func (x *RemoveUserFromAllGroupFilesRequest) GetGroupIds() []string {
	if x != nil {
		return x.GroupIds
	}
	return nil
}

func (x *RemoveUserFromAllGroupFilesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// MarkLinksDeleted - mark file links as soft deleted
type MarkLinksDeletedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkIds       []string               `protobuf:"bytes,1,rep,name=link_ids,json=linkIds,proto3" json:"link_ids,omitempty"` // File link IDs to mark as deleted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkLinksDeletedRequest) Reset() {
	*x = MarkLinksDeletedRequest{}
	mi := &file_proto_files_files_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkLinksDeletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkLinksDeletedRequest) ProtoMessage() {}

func (x *MarkLinksDeletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkLinksDeletedRequest.ProtoReflect.Descriptor instead.
func (*MarkLinksDeletedRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{22}
}

func (x *MarkLinksDeletedRequest) GetLinkIds() []string {
	if x != nil {
		return x.LinkIds
	}
	return nil
}

// RestoreLinks - restore soft-deleted file links
type RestoreLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkIds       []string               `protobuf:"bytes,1,rep,name=link_ids,json=linkIds,proto3" json:"link_ids,omitempty"` // File link IDs to restore
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreLinksRequest) Reset() {
	*x = RestoreLinksRequest{}
	mi := &file_proto_files_files_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreLinksRequest) ProtoMessage() {}

func (x *RestoreLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreLinksRequest.ProtoReflect.Descriptor instead.
func (*RestoreLinksRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{23}
}

func (x *RestoreLinksRequest) GetLinkIds() []string {
	if x != nil {
		return x.LinkIds
	}
	return nil
}

// PermanentlyDeleteLinks - permanently delete links and orphan files
type PermanentlyDeleteLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkIds       []string               `protobuf:"bytes,1,rep,name=link_ids,json=linkIds,proto3" json:"link_ids,omitempty"` // File link IDs to permanently delete
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermanentlyDeleteLinksRequest) Reset() {
	*x = PermanentlyDeleteLinksRequest{}
	mi := &file_proto_files_files_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermanentlyDeleteLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermanentlyDeleteLinksRequest) ProtoMessage() {}

func (x *PermanentlyDeleteLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermanentlyDeleteLinksRequest.ProtoReflect.Descriptor instead.
func (*PermanentlyDeleteLinksRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{24}
}

func (x *PermanentlyDeleteLinksRequest) GetLinkIds() []string {
	if x != nil {
		return x.LinkIds
	}
	return nil
}

type PermanentlyDeleteLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedLinks  int32                  `protobuf:"varint,1,opt,name=deleted_links,json=deletedLinks,proto3" json:"deleted_links,omitempty"` // Number of file links deleted
	DeletedFiles  int32                  `protobuf:"varint,2,opt,name=deleted_files,json=deletedFiles,proto3" json:"deleted_files,omitempty"` // Number of orphan files deleted from storage
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermanentlyDeleteLinksResponse) Reset() {
	*x = PermanentlyDeleteLinksResponse{}
	mi := &file_proto_files_files_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermanentlyDeleteLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermanentlyDeleteLinksResponse) ProtoMessage() {}

func (x *PermanentlyDeleteLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_files_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermanentlyDeleteLinksResponse.ProtoReflect.Descriptor instead.
func (*PermanentlyDeleteLinksResponse) Descriptor() ([]byte, []int) {
	return file_proto_files_files_proto_rawDescGZIP(), []int{25}
}

func (x *PermanentlyDeleteLinksResponse) GetDeletedLinks() int32 {
	if x != nil {
		return x.DeletedLinks
	}
	return 0
}

func (x *PermanentlyDeleteLinksResponse) GetDeletedFiles() int32 {
	if x != nil {
		return x.DeletedFiles
	}
	return 0
}

var File_proto_files_files_proto protoreflect.FileDescriptor

const file_proto_files_files_proto_rawDesc = "" +
	"\n" +
	"\x17proto/files/files.proto\x12\x05files\x1a\x1bgoogle/protobuf/empty.proto\"\xb0\x01\n" +
	"\x13AddLocalFileRequest\x12(\n" +
	"\x10server_file_path\x18\x01 \x01(\tR\x0eserverFilePath\x12+\n" +
	"\x11original_filename\x18\x02 \x01(\tR\x10originalFilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x1f\n" +
	"\vuploaded_by\x18\x04 \x01(\tR\n" +
	"uploadedBy\"\xc8\x01\n" +
	"\x14AddLocalFileResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x17\n" +
	"\alink_id\x18\x02 \x01(\tR\x06linkId\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12+\n" +
	"\x11original_filename\x18\x04 \x01(\tR\x10originalFilename\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\"O\n" +
	"\x15CreateFileLinkRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1d\n" +
	"\n" +
	"created_by\x18\x02 \x01(\tR\tcreatedBy\"J\n" +
	"\x16CreateFileLinkResponse\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\"n\n" +
	"\x17GrantPermissionsRequest\x12\x19\n" +
	"\blink_ids\x18\x01 \x03(\tR\alinkIds\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\tR\auserIds\x12\x1d\n" +
	"\n" +
	"granter_id\x18\x03 \x01(\tR\tgranterId\"N\n" +
	"\x18RevokePermissionsRequest\x12\x19\n" +
	"\blink_ids\x18\x01 \x03(\tR\alinkIds\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"3\n" +
	"\x18GetFileIDByLinkIDRequest\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\"4\n" +
	"\x19GetFileIDByLinkIDResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"5\n" +
	"\x18GetFilesByLinkIDsRequest\x12\x19\n" +
	"\blink_ids\x18\x01 \x03(\tR\alinkIds\"\xc2\x01\n" +
	"\x0eFileAttachment\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12+\n" +
	"\x11original_filename\x18\x04 \x01(\tR\x10originalFilename\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\"H\n" +
	"\x19GetFilesByLinkIDsResponse\x12+\n" +
	"\x05files\x18\x01 \x03(\v2\x15.files.FileAttachmentR\x05files\"\x8c\x01\n" +
	"\tFileGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bcan_read\x18\x03 \x01(\bR\acanRead\x12\x1d\n" +
	"\n" +
	"can_delete\x18\x04 \x01(\bR\tcanDelete\x12!\n" +
	"\fcan_transfer\x18\x05 \x01(\bR\vcanTransfer\"\x89\x01\n" +
	"\x16CreateFileGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bcan_read\x18\x02 \x01(\bR\acanRead\x12\x1d\n" +
	"\n" +
	"can_delete\x18\x03 \x01(\bR\tcanDelete\x12!\n" +
	"\fcan_transfer\x18\x04 \x01(\bR\vcanTransfer\"A\n" +
	"\x17CreateFileGroupResponse\x12&\n" +
	"\x05group\x18\x01 \x01(\v2\x10.files.FileGroupR\x05group\"3\n" +
	"\x16DeleteFileGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"K\n" +
	"\x15AddUserToGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"P\n" +
	"\x1aRemoveUserFromGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"[\n" +
	"\x1aAddFileLinkToGroupsRequest\x12 \n" +
	"\ffile_link_id\x18\x01 \x01(\tR\n" +
	"fileLinkId\x12\x1b\n" +
	"\tgroup_ids\x18\x02 \x03(\tR\bgroupIds\"3\n" +
	"\x16GetFilesByGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"X\n" +
	"\fFileLinkInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x1f\n" +
	"\vuploaded_by\x18\x03 \x01(\tR\n" +
	"uploadedBy\"M\n" +
	"\x17GetFilesByGroupResponse\x122\n" +
	"\n" +
	"file_links\x18\x01 \x03(\v2\x13.files.FileLinkInfoR\tfileLinks\"Z\n" +
	"\"RemoveUserFromAllGroupFilesRequest\x12\x1b\n" +
	"\tgroup_ids\x18\x01 \x03(\tR\bgroupIds\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"4\n" +
	"\x17MarkLinksDeletedRequest\x12\x19\n" +
	"\blink_ids\x18\x01 \x03(\tR\alinkIds\"0\n" +
	"\x13RestoreLinksRequest\x12\x19\n" +
	"\blink_ids\x18\x01 \x03(\tR\alinkIds\":\n" +
	"\x1dPermanentlyDeleteLinksRequest\x12\x19\n" +
	"\blink_ids\x18\x01 \x03(\tR\alinkIds\"j\n" +
	"\x1ePermanentlyDeleteLinksResponse\x12#\n" +
	"\rdeleted_links\x18\x01 \x01(\x05R\fdeletedLinks\x12#\n" +
	"\rdeleted_files\x18\x02 \x01(\x05R\fdeletedFiles2\xa3\n" +
	"\n" +
	"\fFilesService\x12G\n" +
	"\fAddLocalFile\x12\x1a.files.AddLocalFileRequest\x1a\x1b.files.AddLocalFileResponse\x12M\n" +
	"\x0eCreateFileLink\x12\x1c.files.CreateFileLinkRequest\x1a\x1d.files.CreateFileLinkResponse\x12J\n" +
	"\x10GrantPermissions\x12\x1e.files.GrantPermissionsRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\x11RevokePermissions\x12\x1f.files.RevokePermissionsRequest\x1a\x16.google.protobuf.Empty\x12V\n" +
	"\x11GetFileIDByLinkID\x12\x1f.files.GetFileIDByLinkIDRequest\x1a .files.GetFileIDByLinkIDResponse\x12V\n" +
	"\x11GetFilesByLinkIDs\x12\x1f.files.GetFilesByLinkIDsRequest\x1a .files.GetFilesByLinkIDsResponse\x12P\n" +
	"\x0fCreateFileGroup\x12\x1d.files.CreateFileGroupRequest\x1a\x1e.files.CreateFileGroupResponse\x12H\n" +
	"\x0fDeleteFileGroup\x12\x1d.files.DeleteFileGroupRequest\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\x0eAddUserToGroup\x12\x1c.files.AddUserToGroupRequest\x1a\x16.google.protobuf.Empty\x12P\n" +
	"\x13RemoveUserFromGroup\x12!.files.RemoveUserFromGroupRequest\x1a\x16.google.protobuf.Empty\x12P\n" +
	"\x13AddFileLinkToGroups\x12!.files.AddFileLinkToGroupsRequest\x1a\x16.google.protobuf.Empty\x12P\n" +
	"\x0fGetFilesByGroup\x12\x1d.files.GetFilesByGroupRequest\x1a\x1e.files.GetFilesByGroupResponse\x12`\n" +
	"\x1bRemoveUserFromAllGroupFiles\x12).files.RemoveUserFromAllGroupFilesRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\x10MarkLinksDeleted\x12\x1e.files.MarkLinksDeletedRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\fRestoreLinks\x12\x1a.files.RestoreLinksRequest\x1a\x16.google.protobuf.Empty\x12e\n" +
	"\x16PermanentlyDeleteLinks\x12$.files.PermanentlyDeleteLinksRequest\x1a%.files.PermanentlyDeleteLinksResponseB*Z(github.com/icegreg/chat-smpl/proto/filesb\x06proto3"

var (
	file_proto_files_files_proto_rawDescOnce sync.Once
	file_proto_files_files_proto_rawDescData []byte
)

func file_proto_files_files_proto_rawDescGZIP() []byte {
	file_proto_files_files_proto_rawDescOnce.Do(func() {
		file_proto_files_files_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_files_files_proto_rawDesc), len(file_proto_files_files_proto_rawDesc)))
	})
	return file_proto_files_files_proto_rawDescData
}

var file_proto_files_files_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_files_files_proto_goTypes = []any{
	(*AddLocalFileRequest)(nil),                // 0: files.AddLocalFileRequest
	(*AddLocalFileResponse)(nil),               // 1: files.AddLocalFileResponse
	(*CreateFileLinkRequest)(nil),              // 2: files.CreateFileLinkRequest
	(*CreateFileLinkResponse)(nil),             // 3: files.CreateFileLinkResponse
	(*GrantPermissionsRequest)(nil),            // 4: files.GrantPermissionsRequest
	(*RevokePermissionsRequest)(nil),           // 5: files.RevokePermissionsRequest
	(*GetFileIDByLinkIDRequest)(nil),           // 6: files.GetFileIDByLinkIDRequest
	(*GetFileIDByLinkIDResponse)(nil),          // 7: files.GetFileIDByLinkIDResponse
	(*GetFilesByLinkIDsRequest)(nil),           // 8: files.GetFilesByLinkIDsRequest
	(*FileAttachment)(nil),                     // 9: files.FileAttachment
	(*GetFilesByLinkIDsResponse)(nil),          // 10: files.GetFilesByLinkIDsResponse
	(*FileGroup)(nil),                          // 11: files.FileGroup
	(*CreateFileGroupRequest)(nil),             // 12: files.CreateFileGroupRequest
	(*CreateFileGroupResponse)(nil),            // 13: files.CreateFileGroupResponse
	(*DeleteFileGroupRequest)(nil),             // 14: files.DeleteFileGroupRequest
	(*AddUserToGroupRequest)(nil),              // 15: files.AddUserToGroupRequest
	(*RemoveUserFromGroupRequest)(nil),         // 16: files.RemoveUserFromGroupRequest
	(*AddFileLinkToGroupsRequest)(nil),         // 17: files.AddFileLinkToGroupsRequest
	(*GetFilesByGroupRequest)(nil),             // 18: files.GetFilesByGroupRequest
	(*FileLinkInfo)(nil),                       // 19: files.FileLinkInfo
	(*GetFilesByGroupResponse)(nil),            // 20: files.GetFilesByGroupResponse
	(*RemoveUserFromAllGroupFilesRequest)(nil), // 21: files.RemoveUserFromAllGroupFilesRequest
	(*MarkLinksDeletedRequest)(nil),            // 22: files.MarkLinksDeletedRequest
	(*RestoreLinksRequest)(nil),                // 23: files.RestoreLinksRequest
	(*PermanentlyDeleteLinksRequest)(nil),      // 24: files.PermanentlyDeleteLinksRequest
	(*PermanentlyDeleteLinksResponse)(nil),     // 25: files.PermanentlyDeleteLinksResponse
	(*emptypb.Empty)(nil),                      // 26: google.protobuf.Empty
}
var file_proto_files_files_proto_depIdxs = []int32{
	9,  // 0: files.GetFilesByLinkIDsResponse.files:type_name -> files.FileAttachment
	11, // 1: files.CreateFileGroupResponse.group:type_name -> files.FileGroup
	19, // 2: files.GetFilesByGroupResponse.file_links:type_name -> files.FileLinkInfo
	0,  // 3: files.FilesService.AddLocalFile:input_type -> files.AddLocalFileRequest
	2,  // 4: files.FilesService.CreateFileLink:input_type -> files.CreateFileLinkRequest
	4,  // 5: files.FilesService.GrantPermissions:input_type -> files.GrantPermissionsRequest
	5,  // 6: files.FilesService.RevokePermissions:input_type -> files.RevokePermissionsRequest
	6,  // 7: files.FilesService.GetFileIDByLinkID:input_type -> files.GetFileIDByLinkIDRequest
	8,  // 8: files.FilesService.GetFilesByLinkIDs:input_type -> files.GetFilesByLinkIDsRequest
	12, // 9: files.FilesService.CreateFileGroup:input_type -> files.CreateFileGroupRequest
	14, // 10: files.FilesService.DeleteFileGroup:input_type -> files.DeleteFileGroupRequest
	15, // 11: files.FilesService.AddUserToGroup:input_type -> files.AddUserToGroupRequest
	16, // 12: files.FilesService.RemoveUserFromGroup:input_type -> files.RemoveUserFromGroupRequest
	17, // 13: files.FilesService.AddFileLinkToGroups:input_type -> files.AddFileLinkToGroupsRequest
	18, // 14: files.FilesService.GetFilesByGroup:input_type -> files.GetFilesByGroupRequest
	21, // 15: files.FilesService.RemoveUserFromAllGroupFiles:input_type -> files.RemoveUserFromAllGroupFilesRequest
	22, // 16: files.FilesService.MarkLinksDeleted:input_type -> files.MarkLinksDeletedRequest
	23, // 17: files.FilesService.RestoreLinks:input_type -> files.RestoreLinksRequest
	24, // 18: files.FilesService.PermanentlyDeleteLinks:input_type -> files.PermanentlyDeleteLinksRequest
	1,  // 19: files.FilesService.AddLocalFile:output_type -> files.AddLocalFileResponse
	3,  // 20: files.FilesService.CreateFileLink:output_type -> files.CreateFileLinkResponse
	26, // 21: files.FilesService.GrantPermissions:output_type -> google.protobuf.Empty
	26, // 22: files.FilesService.RevokePermissions:output_type -> google.protobuf.Empty
	7,  // 23: files.FilesService.GetFileIDByLinkID:output_type -> files.GetFileIDByLinkIDResponse
	10, // 24: files.FilesService.GetFilesByLinkIDs:output_type -> files.GetFilesByLinkIDsResponse
	13, // 25: files.FilesService.CreateFileGroup:output_type -> files.CreateFileGroupResponse
	26, // 26: files.FilesService.DeleteFileGroup:output_type -> google.protobuf.Empty
	26, // 27: files.FilesService.AddUserToGroup:output_type -> google.protobuf.Empty
	26, // 28: files.FilesService.RemoveUserFromGroup:output_type -> google.protobuf.Empty
	26, // 29: files.FilesService.AddFileLinkToGroups:output_type -> google.protobuf.Empty
	20, // 30: files.FilesService.GetFilesByGroup:output_type -> files.GetFilesByGroupResponse
	26, // 31: files.FilesService.RemoveUserFromAllGroupFiles:output_type -> google.protobuf.Empty
	26, // 32: files.FilesService.MarkLinksDeleted:output_type -> google.protobuf.Empty
	26, // 33: files.FilesService.RestoreLinks:output_type -> google.protobuf.Empty
	25, // 34: files.FilesService.PermanentlyDeleteLinks:output_type -> files.PermanentlyDeleteLinksResponse
	19, // [19:35] is the sub-list for method output_type
	3,  // [3:19] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_files_files_proto_init() }
func file_proto_files_files_proto_init() {
	if File_proto_files_files_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_files_files_proto_rawDesc), len(file_proto_files_files_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_files_files_proto_goTypes,
		DependencyIndexes: file_proto_files_files_proto_depIdxs,
		MessageInfos:      file_proto_files_files_proto_msgTypes,
	}.Build()
	File_proto_files_files_proto = out.File
	file_proto_files_files_proto_goTypes = nil
	file_proto_files_files_proto_depIdxs = nil
}
