// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.4
// source: proto/files/files.proto

package files

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FilesService_AddLocalFile_FullMethodName                = "/files.FilesService/AddLocalFile"
	FilesService_CreateFileLink_FullMethodName              = "/files.FilesService/CreateFileLink"
	FilesService_GrantPermissions_FullMethodName            = "/files.FilesService/GrantPermissions"
	FilesService_RevokePermissions_FullMethodName           = "/files.FilesService/RevokePermissions"
	FilesService_GetFileIDByLinkID_FullMethodName           = "/files.FilesService/GetFileIDByLinkID"
	FilesService_GetFilesByLinkIDs_FullMethodName           = "/files.FilesService/GetFilesByLinkIDs"
	FilesService_CreateFileGroup_FullMethodName             = "/files.FilesService/CreateFileGroup"
	FilesService_DeleteFileGroup_FullMethodName             = "/files.FilesService/DeleteFileGroup"
	FilesService_AddUserToGroup_FullMethodName              = "/files.FilesService/AddUserToGroup"
	FilesService_RemoveUserFromGroup_FullMethodName         = "/files.FilesService/RemoveUserFromGroup"
	FilesService_AddFileLinkToGroups_FullMethodName         = "/files.FilesService/AddFileLinkToGroups"
	FilesService_GetFilesByGroup_FullMethodName             = "/files.FilesService/GetFilesByGroup"
	FilesService_RemoveUserFromAllGroupFiles_FullMethodName = "/files.FilesService/RemoveUserFromAllGroupFiles"
	FilesService_MarkLinksDeleted_FullMethodName            = "/files.FilesService/MarkLinksDeleted"
	FilesService_RestoreLinks_FullMethodName                = "/files.FilesService/RestoreLinks"
	FilesService_PermanentlyDeleteLinks_FullMethodName      = "/files.FilesService/PermanentlyDeleteLinks"
)

// FilesServiceClient is the client API for FilesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FilesServiceClient interface {
	// Add a local file from server filesystem
	AddLocalFile(ctx context.Context, in *AddLocalFileRequest, opts ...grpc.CallOption) (*AddLocalFileResponse, error)
	// Create a new FileLink for an existing file (for message forwarding)
	CreateFileLink(ctx context.Context, in *CreateFileLinkRequest, opts ...grpc.CallOption) (*CreateFileLinkResponse, error)
	// Grant permissions to users for file links (individual permissions)
	GrantPermissions(ctx context.Context, in *GrantPermissionsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Revoke permissions from a user for file links
	RevokePermissions(ctx context.Context, in *RevokePermissionsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Get file_id by link_id (for forward operation)
	GetFileIDByLinkID(ctx context.Context, in *GetFileIDByLinkIDRequest, opts ...grpc.CallOption) (*GetFileIDByLinkIDResponse, error)
	// Get file metadata by link IDs (batch)
	GetFilesByLinkIDs(ctx context.Context, in *GetFilesByLinkIDsRequest, opts ...grpc.CallOption) (*GetFilesByLinkIDsResponse, error)
	// ============ File Groups Management ============
	// Create a new file group with permissions
	CreateFileGroup(ctx context.Context, in *CreateFileGroupRequest, opts ...grpc.CallOption) (*CreateFileGroupResponse, error)
	// Delete a file group
	DeleteFileGroup(ctx context.Context, in *DeleteFileGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Add a user to a file group
	AddUserToGroup(ctx context.Context, in *AddUserToGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Remove a user from a file group
	RemoveUserFromGroup(ctx context.Context, in *RemoveUserFromGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Associate file links with groups
	AddFileLinkToGroups(ctx context.Context, in *AddFileLinkToGroupsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Get all file links in a group
	GetFilesByGroup(ctx context.Context, in *GetFilesByGroupRequest, opts ...grpc.CallOption) (*GetFilesByGroupResponse, error)
	// Remove user from all groups and revoke permissions on group files
	RemoveUserFromAllGroupFiles(ctx context.Context, in *RemoveUserFromAllGroupFilesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ============ File Links Soft Delete ============
	// Mark file links as deleted (soft delete for message deletion)
	MarkLinksDeleted(ctx context.Context, in *MarkLinksDeletedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Restore soft-deleted file links (for message restoration)
	RestoreLinks(ctx context.Context, in *RestoreLinksRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Permanently delete file links and orphan files (for cleanup job)
	PermanentlyDeleteLinks(ctx context.Context, in *PermanentlyDeleteLinksRequest, opts ...grpc.CallOption) (*PermanentlyDeleteLinksResponse, error)
}

type filesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFilesServiceClient(cc grpc.ClientConnInterface) FilesServiceClient {
	return &filesServiceClient{cc}
}

func (c *filesServiceClient) AddLocalFile(ctx context.Context, in *AddLocalFileRequest, opts ...grpc.CallOption) (*AddLocalFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddLocalFileResponse)
	err := c.cc.Invoke(ctx, FilesService_AddLocalFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesServiceClient) CreateFileLink(ctx context.Context, in *CreateFileLinkRequest, opts ...grpc.CallOption) (*CreateFileLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFileLinkResponse)
	err := c.cc.Invoke(ctx, FilesService_CreateFileLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesServiceClient) GrantPermissions(ctx context.Context, in *GrantPermissionsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FilesService_GrantPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesServiceClient) RevokePermissions(ctx context.Context, in *RevokePermissionsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FilesService_RevokePermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesServiceClient) GetFileIDByLinkID(ctx context.Context, in *GetFileIDByLinkIDRequest, opts ...grpc.CallOption) (*GetFileIDByLinkIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileIDByLinkIDResponse)
	err := c.cc.Invoke(ctx, FilesService_GetFileIDByLinkID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesServiceClient) GetFilesByLinkIDs(ctx context.Context, in *GetFilesByLinkIDsRequest, opts ...grpc.CallOption) (*GetFilesByLinkIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFilesByLinkIDsResponse)
	err := c.cc.Invoke(ctx, FilesService_GetFilesByLinkIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesServiceClient) CreateFileGroup(ctx context.Context, in *CreateFileGroupRequest, opts ...grpc.CallOption) (*CreateFileGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFileGroupResponse)
	err := c.cc.Invoke(ctx, FilesService_CreateFileGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesServiceClient) DeleteFileGroup(ctx context.Context, in *DeleteFileGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FilesService_DeleteFileGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesServiceClient) AddUserToGroup(ctx context.Context, in *AddUserToGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FilesService_AddUserToGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesServiceClient) RemoveUserFromGroup(ctx context.Context, in *RemoveUserFromGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FilesService_RemoveUserFromGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesServiceClient) AddFileLinkToGroups(ctx context.Context, in *AddFileLinkToGroupsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FilesService_AddFileLinkToGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesServiceClient) GetFilesByGroup(ctx context.Context, in *GetFilesByGroupRequest, opts ...grpc.CallOption) (*GetFilesByGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFilesByGroupResponse)
	err := c.cc.Invoke(ctx, FilesService_GetFilesByGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesServiceClient) RemoveUserFromAllGroupFiles(ctx context.Context, in *RemoveUserFromAllGroupFilesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FilesService_RemoveUserFromAllGroupFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesServiceClient) MarkLinksDeleted(ctx context.Context, in *MarkLinksDeletedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FilesService_MarkLinksDeleted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesServiceClient) RestoreLinks(ctx context.Context, in *RestoreLinksRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FilesService_RestoreLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesServiceClient) PermanentlyDeleteLinks(ctx context.Context, in *PermanentlyDeleteLinksRequest, opts ...grpc.CallOption) (*PermanentlyDeleteLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PermanentlyDeleteLinksResponse)
	err := c.cc.Invoke(ctx, FilesService_PermanentlyDeleteLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FilesServiceServer is the server API for FilesService service.
// All implementations must embed UnimplementedFilesServiceServer
// for forward compatibility.
type FilesServiceServer interface {
	// Add a local file from server filesystem
	AddLocalFile(context.Context, *AddLocalFileRequest) (*AddLocalFileResponse, error)
	// Create a new FileLink for an existing file (for message forwarding)
	CreateFileLink(context.Context, *CreateFileLinkRequest) (*CreateFileLinkResponse, error)
	// Grant permissions to users for file links (individual permissions)
	GrantPermissions(context.Context, *GrantPermissionsRequest) (*emptypb.Empty, error)
	// Revoke permissions from a user for file links
	RevokePermissions(context.Context, *RevokePermissionsRequest) (*emptypb.Empty, error)
	// Get file_id by link_id (for forward operation)
	GetFileIDByLinkID(context.Context, *GetFileIDByLinkIDRequest) (*GetFileIDByLinkIDResponse, error)
	// Get file metadata by link IDs (batch)
	GetFilesByLinkIDs(context.Context, *GetFilesByLinkIDsRequest) (*GetFilesByLinkIDsResponse, error)
	// ============ File Groups Management ============
	// Create a new file group with permissions
	CreateFileGroup(context.Context, *CreateFileGroupRequest) (*CreateFileGroupResponse, error)
	// Delete a file group
	DeleteFileGroup(context.Context, *DeleteFileGroupRequest) (*emptypb.Empty, error)
	// Add a user to a file group
	AddUserToGroup(context.Context, *AddUserToGroupRequest) (*emptypb.Empty, error)
	// Remove a user from a file group
	RemoveUserFromGroup(context.Context, *RemoveUserFromGroupRequest) (*emptypb.Empty, error)
	// Associate file links with groups
	AddFileLinkToGroups(context.Context, *AddFileLinkToGroupsRequest) (*emptypb.Empty, error)
	// Get all file links in a group
	GetFilesByGroup(context.Context, *GetFilesByGroupRequest) (*GetFilesByGroupResponse, error)
	// Remove user from all groups and revoke permissions on group files
	RemoveUserFromAllGroupFiles(context.Context, *RemoveUserFromAllGroupFilesRequest) (*emptypb.Empty, error)
	// ============ File Links Soft Delete ============
	// Mark file links as deleted (soft delete for message deletion)
	MarkLinksDeleted(context.Context, *MarkLinksDeletedRequest) (*emptypb.Empty, error)
	// Restore soft-deleted file links (for message restoration)
	RestoreLinks(context.Context, *RestoreLinksRequest) (*emptypb.Empty, error)
	// Permanently delete file links and orphan files (for cleanup job)
	PermanentlyDeleteLinks(context.Context, *PermanentlyDeleteLinksRequest) (*PermanentlyDeleteLinksResponse, error)
	mustEmbedUnimplementedFilesServiceServer()
}

// UnimplementedFilesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFilesServiceServer struct{}

func (UnimplementedFilesServiceServer) AddLocalFile(context.Context, *AddLocalFileRequest) (*AddLocalFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLocalFile not implemented")
}
func (UnimplementedFilesServiceServer) CreateFileLink(context.Context, *CreateFileLinkRequest) (*CreateFileLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFileLink not implemented")
}
func (UnimplementedFilesServiceServer) GrantPermissions(context.Context, *GrantPermissionsRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrantPermissions not implemented")
}
func (UnimplementedFilesServiceServer) RevokePermissions(context.Context, *RevokePermissionsRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokePermissions not implemented")
}
func (UnimplementedFilesServiceServer) GetFileIDByLinkID(context.Context, *GetFileIDByLinkIDRequest) (*GetFileIDByLinkIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileIDByLinkID not implemented")
}
func (UnimplementedFilesServiceServer) GetFilesByLinkIDs(context.Context, *GetFilesByLinkIDsRequest) (*GetFilesByLinkIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFilesByLinkIDs not implemented")
}
func (UnimplementedFilesServiceServer) CreateFileGroup(context.Context, *CreateFileGroupRequest) (*CreateFileGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFileGroup not implemented")
}
func (UnimplementedFilesServiceServer) DeleteFileGroup(context.Context, *DeleteFileGroupRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFileGroup not implemented")
}
func (UnimplementedFilesServiceServer) AddUserToGroup(context.Context, *AddUserToGroupRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUserToGroup not implemented")
}
func (UnimplementedFilesServiceServer) RemoveUserFromGroup(context.Context, *RemoveUserFromGroupRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveUserFromGroup not implemented")
}
func (UnimplementedFilesServiceServer) AddFileLinkToGroups(context.Context, *AddFileLinkToGroupsRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFileLinkToGroups not implemented")
}
func (UnimplementedFilesServiceServer) GetFilesByGroup(context.Context, *GetFilesByGroupRequest) (*GetFilesByGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFilesByGroup not implemented")
}
func (UnimplementedFilesServiceServer) RemoveUserFromAllGroupFiles(context.Context, *RemoveUserFromAllGroupFilesRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveUserFromAllGroupFiles not implemented")
}
func (UnimplementedFilesServiceServer) MarkLinksDeleted(context.Context, *MarkLinksDeletedRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkLinksDeleted not implemented")
}
func (UnimplementedFilesServiceServer) RestoreLinks(context.Context, *RestoreLinksRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreLinks not implemented")
}
func (UnimplementedFilesServiceServer) PermanentlyDeleteLinks(context.Context, *PermanentlyDeleteLinksRequest) (*PermanentlyDeleteLinksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PermanentlyDeleteLinks not implemented")
}
func (UnimplementedFilesServiceServer) mustEmbedUnimplementedFilesServiceServer() {}
func (UnimplementedFilesServiceServer) testEmbeddedByValue()                      {}

// UnsafeFilesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FilesServiceServer will
// result in compilation errors.
type UnsafeFilesServiceServer interface {
	mustEmbedUnimplementedFilesServiceServer()
}

func RegisterFilesServiceServer(s grpc.ServiceRegistrar, srv FilesServiceServer) {
	// If the following call pancis, it indicates UnimplementedFilesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FilesService_ServiceDesc, srv)
}

func _FilesService_AddLocalFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddLocalFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesServiceServer).AddLocalFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilesService_AddLocalFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesServiceServer).AddLocalFile(ctx, req.(*AddLocalFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesService_CreateFileLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFileLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesServiceServer).CreateFileLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilesService_CreateFileLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesServiceServer).CreateFileLink(ctx, req.(*CreateFileLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesService_GrantPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesServiceServer).GrantPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilesService_GrantPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesServiceServer).GrantPermissions(ctx, req.(*GrantPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesService_RevokePermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokePermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesServiceServer).RevokePermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilesService_RevokePermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesServiceServer).RevokePermissions(ctx, req.(*RevokePermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesService_GetFileIDByLinkID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileIDByLinkIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesServiceServer).GetFileIDByLinkID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilesService_GetFileIDByLinkID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesServiceServer).GetFileIDByLinkID(ctx, req.(*GetFileIDByLinkIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesService_GetFilesByLinkIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFilesByLinkIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesServiceServer).GetFilesByLinkIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilesService_GetFilesByLinkIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesServiceServer).GetFilesByLinkIDs(ctx, req.(*GetFilesByLinkIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesService_CreateFileGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFileGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesServiceServer).CreateFileGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilesService_CreateFileGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesServiceServer).CreateFileGroup(ctx, req.(*CreateFileGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesService_DeleteFileGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesServiceServer).DeleteFileGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilesService_DeleteFileGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesServiceServer).DeleteFileGroup(ctx, req.(*DeleteFileGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesService_AddUserToGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserToGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesServiceServer).AddUserToGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilesService_AddUserToGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesServiceServer).AddUserToGroup(ctx, req.(*AddUserToGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesService_RemoveUserFromGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUserFromGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesServiceServer).RemoveUserFromGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilesService_RemoveUserFromGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesServiceServer).RemoveUserFromGroup(ctx, req.(*RemoveUserFromGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesService_AddFileLinkToGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFileLinkToGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesServiceServer).AddFileLinkToGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilesService_AddFileLinkToGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesServiceServer).AddFileLinkToGroups(ctx, req.(*AddFileLinkToGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesService_GetFilesByGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFilesByGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesServiceServer).GetFilesByGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilesService_GetFilesByGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesServiceServer).GetFilesByGroup(ctx, req.(*GetFilesByGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesService_RemoveUserFromAllGroupFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUserFromAllGroupFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesServiceServer).RemoveUserFromAllGroupFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilesService_RemoveUserFromAllGroupFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesServiceServer).RemoveUserFromAllGroupFiles(ctx, req.(*RemoveUserFromAllGroupFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesService_MarkLinksDeleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkLinksDeletedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesServiceServer).MarkLinksDeleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilesService_MarkLinksDeleted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesServiceServer).MarkLinksDeleted(ctx, req.(*MarkLinksDeletedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesService_RestoreLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesServiceServer).RestoreLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilesService_RestoreLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesServiceServer).RestoreLinks(ctx, req.(*RestoreLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesService_PermanentlyDeleteLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermanentlyDeleteLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesServiceServer).PermanentlyDeleteLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilesService_PermanentlyDeleteLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesServiceServer).PermanentlyDeleteLinks(ctx, req.(*PermanentlyDeleteLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FilesService_ServiceDesc is the grpc.ServiceDesc for FilesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FilesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "files.FilesService",
	HandlerType: (*FilesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddLocalFile",
			Handler:    _FilesService_AddLocalFile_Handler,
		},
		{
			MethodName: "CreateFileLink",
			Handler:    _FilesService_CreateFileLink_Handler,
		},
		{
			MethodName: "GrantPermissions",
			Handler:    _FilesService_GrantPermissions_Handler,
		},
		{
			MethodName: "RevokePermissions",
			Handler:    _FilesService_RevokePermissions_Handler,
		},
		{
			MethodName: "GetFileIDByLinkID",
			Handler:    _FilesService_GetFileIDByLinkID_Handler,
		},
		{
			MethodName: "GetFilesByLinkIDs",
			Handler:    _FilesService_GetFilesByLinkIDs_Handler,
		},
		{
			MethodName: "CreateFileGroup",
			Handler:    _FilesService_CreateFileGroup_Handler,
		},
		{
			MethodName: "DeleteFileGroup",
			Handler:    _FilesService_DeleteFileGroup_Handler,
		},
		{
			MethodName: "AddUserToGroup",
			Handler:    _FilesService_AddUserToGroup_Handler,
		},
		{
			MethodName: "RemoveUserFromGroup",
			Handler:    _FilesService_RemoveUserFromGroup_Handler,
		},
		{
			MethodName: "AddFileLinkToGroups",
			Handler:    _FilesService_AddFileLinkToGroups_Handler,
		},
		{
			MethodName: "GetFilesByGroup",
			Handler:    _FilesService_GetFilesByGroup_Handler,
		},
		{
			MethodName: "RemoveUserFromAllGroupFiles",
			Handler:    _FilesService_RemoveUserFromAllGroupFiles_Handler,
		},
		{
			MethodName: "MarkLinksDeleted",
			Handler:    _FilesService_MarkLinksDeleted_Handler,
		},
		{
			MethodName: "RestoreLinks",
			Handler:    _FilesService_RestoreLinks_Handler,
		},
		{
			MethodName: "PermanentlyDeleteLinks",
			Handler:    _FilesService_PermanentlyDeleteLinks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/files/files.proto",
}
