// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.4
// source: proto/presence/presence.proto

package presence

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PresenceService_SetStatus_FullMethodName         = "/presence.PresenceService/SetStatus"
	PresenceService_GetPresence_FullMethodName       = "/presence.PresenceService/GetPresence"
	PresenceService_GetPresencesBatch_FullMethodName = "/presence.PresenceService/GetPresencesBatch"
	PresenceService_UserConnected_FullMethodName     = "/presence.PresenceService/UserConnected"
	PresenceService_UserDisconnected_FullMethodName  = "/presence.PresenceService/UserDisconnected"
)

// PresenceServiceClient is the client API for PresenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PresenceService handles user presence and status
type PresenceServiceClient interface {
	// SetStatus sets user's status (available, busy, away, dnd)
	SetStatus(ctx context.Context, in *SetStatusRequest, opts ...grpc.CallOption) (*SetStatusResponse, error)
	// GetPresence gets presence info for a single user
	GetPresence(ctx context.Context, in *GetPresenceRequest, opts ...grpc.CallOption) (*GetPresenceResponse, error)
	// GetPresencesBatch gets presence info for multiple users
	GetPresencesBatch(ctx context.Context, in *GetPresencesBatchRequest, opts ...grpc.CallOption) (*GetPresencesBatchResponse, error)
	// UserConnected is called when user establishes websocket connection
	UserConnected(ctx context.Context, in *UserConnectedRequest, opts ...grpc.CallOption) (*UserConnectedResponse, error)
	// UserDisconnected is called when user's websocket connection closes
	UserDisconnected(ctx context.Context, in *UserDisconnectedRequest, opts ...grpc.CallOption) (*UserDisconnectedResponse, error)
}

type presenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPresenceServiceClient(cc grpc.ClientConnInterface) PresenceServiceClient {
	return &presenceServiceClient{cc}
}

func (c *presenceServiceClient) SetStatus(ctx context.Context, in *SetStatusRequest, opts ...grpc.CallOption) (*SetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetStatusResponse)
	err := c.cc.Invoke(ctx, PresenceService_SetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *presenceServiceClient) GetPresence(ctx context.Context, in *GetPresenceRequest, opts ...grpc.CallOption) (*GetPresenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPresenceResponse)
	err := c.cc.Invoke(ctx, PresenceService_GetPresence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *presenceServiceClient) GetPresencesBatch(ctx context.Context, in *GetPresencesBatchRequest, opts ...grpc.CallOption) (*GetPresencesBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPresencesBatchResponse)
	err := c.cc.Invoke(ctx, PresenceService_GetPresencesBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *presenceServiceClient) UserConnected(ctx context.Context, in *UserConnectedRequest, opts ...grpc.CallOption) (*UserConnectedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserConnectedResponse)
	err := c.cc.Invoke(ctx, PresenceService_UserConnected_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *presenceServiceClient) UserDisconnected(ctx context.Context, in *UserDisconnectedRequest, opts ...grpc.CallOption) (*UserDisconnectedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserDisconnectedResponse)
	err := c.cc.Invoke(ctx, PresenceService_UserDisconnected_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PresenceServiceServer is the server API for PresenceService service.
// All implementations must embed UnimplementedPresenceServiceServer
// for forward compatibility.
//
// PresenceService handles user presence and status
type PresenceServiceServer interface {
	// SetStatus sets user's status (available, busy, away, dnd)
	SetStatus(context.Context, *SetStatusRequest) (*SetStatusResponse, error)
	// GetPresence gets presence info for a single user
	GetPresence(context.Context, *GetPresenceRequest) (*GetPresenceResponse, error)
	// GetPresencesBatch gets presence info for multiple users
	GetPresencesBatch(context.Context, *GetPresencesBatchRequest) (*GetPresencesBatchResponse, error)
	// UserConnected is called when user establishes websocket connection
	UserConnected(context.Context, *UserConnectedRequest) (*UserConnectedResponse, error)
	// UserDisconnected is called when user's websocket connection closes
	UserDisconnected(context.Context, *UserDisconnectedRequest) (*UserDisconnectedResponse, error)
	mustEmbedUnimplementedPresenceServiceServer()
}

// UnimplementedPresenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPresenceServiceServer struct{}

func (UnimplementedPresenceServiceServer) SetStatus(context.Context, *SetStatusRequest) (*SetStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetStatus not implemented")
}
func (UnimplementedPresenceServiceServer) GetPresence(context.Context, *GetPresenceRequest) (*GetPresenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPresence not implemented")
}
func (UnimplementedPresenceServiceServer) GetPresencesBatch(context.Context, *GetPresencesBatchRequest) (*GetPresencesBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPresencesBatch not implemented")
}
func (UnimplementedPresenceServiceServer) UserConnected(context.Context, *UserConnectedRequest) (*UserConnectedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserConnected not implemented")
}
func (UnimplementedPresenceServiceServer) UserDisconnected(context.Context, *UserDisconnectedRequest) (*UserDisconnectedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserDisconnected not implemented")
}
func (UnimplementedPresenceServiceServer) mustEmbedUnimplementedPresenceServiceServer() {}
func (UnimplementedPresenceServiceServer) testEmbeddedByValue()                         {}

// UnsafePresenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PresenceServiceServer will
// result in compilation errors.
type UnsafePresenceServiceServer interface {
	mustEmbedUnimplementedPresenceServiceServer()
}

func RegisterPresenceServiceServer(s grpc.ServiceRegistrar, srv PresenceServiceServer) {
	// If the following call pancis, it indicates UnimplementedPresenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PresenceService_ServiceDesc, srv)
}

func _PresenceService_SetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresenceServiceServer).SetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PresenceService_SetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresenceServiceServer).SetStatus(ctx, req.(*SetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PresenceService_GetPresence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPresenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresenceServiceServer).GetPresence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PresenceService_GetPresence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresenceServiceServer).GetPresence(ctx, req.(*GetPresenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PresenceService_GetPresencesBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPresencesBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresenceServiceServer).GetPresencesBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PresenceService_GetPresencesBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresenceServiceServer).GetPresencesBatch(ctx, req.(*GetPresencesBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PresenceService_UserConnected_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserConnectedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresenceServiceServer).UserConnected(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PresenceService_UserConnected_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresenceServiceServer).UserConnected(ctx, req.(*UserConnectedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PresenceService_UserDisconnected_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDisconnectedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresenceServiceServer).UserDisconnected(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PresenceService_UserDisconnected_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresenceServiceServer).UserDisconnected(ctx, req.(*UserDisconnectedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PresenceService_ServiceDesc is the grpc.ServiceDesc for PresenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PresenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "presence.PresenceService",
	HandlerType: (*PresenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetStatus",
			Handler:    _PresenceService_SetStatus_Handler,
		},
		{
			MethodName: "GetPresence",
			Handler:    _PresenceService_GetPresence_Handler,
		},
		{
			MethodName: "GetPresencesBatch",
			Handler:    _PresenceService_GetPresencesBatch_Handler,
		},
		{
			MethodName: "UserConnected",
			Handler:    _PresenceService_UserConnected_Handler,
		},
		{
			MethodName: "UserDisconnected",
			Handler:    _PresenceService_UserDisconnected_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/presence/presence.proto",
}
